/* mmv.c generated by valac 0.56.17, the Vala compiler
 * generated from mmv.vala, do not modify */

/*
  mmv

  Copyright (c) 2021-2023 Reuben Thomas.
  Copyright (c) 1990 Vladimir Lanin.

  This program is distributed under the GNU GPL version 3, or, at your
  option, any later version.

  Maintainer: Reuben Thomas <rrt@sc3d.org>

  The original author of mmv was Vladimir Lanin <lanin@csd2.nyu.edu>.

  Many thanks to those who have to contributed to the design
  and/or coding of this program:

  Tom Albrecht:	initial Sys V adaptation, consultation, and testing
  Carl Mascott:	V7 adaptation
  Mark Lewis:	-n flag idea, consultation.
  Dave Bernhold:	upper/lowercase conversion idea.
  Paul Stodghill:	copy option, argv[0] checking.
  Frank Fiamingo:	consultation and testing.
  Tom Jordahl:	bug reports and testing.
  John Lukas, Hugh Redelmeyer, Barry Nelson, John Sauter,
  Phil Dench, John Nelson:
  bug reports.
*/
/* #include "config.h"*/
/* /* NAME_MAX is not guaranteed to exist and its value should really be*/
/*  * obtained with pathconf(), but that doesn't exist on mingw * /*/
/* #ifdef _WIN32*/
/* #define _POSIX_ /* For NAME_MAX in limits.h on mingw * /*/
/* #endif*/

#include <glib.h>
#include <glib-object.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>
#include <mmv.h>
#include <cmdline-vala.h>

#define ESC '\\'
#define SLASH '/'
#define APPENDNAME "mad"
#define COPYNAME "mcp"
#define LINKNAME "mln"
#define MAXWILD 20
#define MAXPATLEN ((gint) _PC_PATH_MAX)
#define INITROOM 10
#define TEMP "$$mmvtmp."
#define TOOLONG "(too long)"
#define EMPTY "(empty)"
#define SLASHSTR "/"
#define PATLONG "%.40s... : pattern too long.\n"
#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

typedef enum  {
	FILE_OP_NORMCOPY = 1 << 0,
	FILE_OP_OVERWRITE = 1 << 1,
	FILE_OP_NORMMOVE = 1 << 2,
	FILE_OP_XMOVE = 1 << 3,
	FILE_OP_APPEND = 1 << 4,
	FILE_OP_HARDLINK = 1 << 5,
	FILE_OP_SYMLINK = 1 << 6,
	FILE_OP_COPY = FILE_OP_NORMCOPY | FILE_OP_OVERWRITE,
	FILE_OP_MOVE = FILE_OP_NORMMOVE | FILE_OP_XMOVE,
	FILE_OP_LINK = FILE_OP_HARDLINK | FILE_OP_SYMLINK
} FileOp;

#define TYPE_FILE_OP (file_op_get_type ())
typedef enum  {
	DELETE_STYLE_ASK,
	DELETE_STYLE_ALL,
	DELETE_STYLE_NO
} DeleteStyle;

#define TYPE_DELETE_STYLE (delete_style_get_type ())
typedef enum  {
	BAD_STYLE_ASK,
	BAD_STYLE_SKIP,
	BAD_STYLE_ABORT
} BadStyle;

#define TYPE_BAD_STYLE (bad_style_get_type ())
typedef enum  {
	RECASE_ACTION_STAY,
	RECASE_ACTION_LOWER,
	RECASE_ACTION_UPPER
} RecaseAction;

#define TYPE_RECASE_ACTION (recase_action_get_type ())
typedef enum  {
	FILE_INFO_TAKEN = 0x01,
	FILE_INFO_LINKERR = 0x02,
	FILE_INFO_INSTICKY = 0x04,
	FILE_INFO_NODEL = 0x08,
	FILE_INFO_KNOWWRITE = 0x10,
	FILE_INFO_CANWRITE = 0x20,
	FILE_INFO_ISDIR = 0x40,
	FILE_INFO_ISLNK = 0x80
} FileInfo;

#define TYPE_FILE_INFO (file_info_get_type ())
typedef enum  {
	DIR_INFO_KNOWWRITE = 0x1,
	DIR_INFO_CANWRITE = 0x2,
	DIR_INFO_NONEXISTENT = 0x4
} DirInfo;

#define TYPE_DIR_INFO (dir_info_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))

VALA_EXTERN FileOp op;
FileOp op = 0U;
VALA_EXTERN BadStyle badstyle;
BadStyle badstyle = 0;
VALA_EXTERN DeleteStyle delstyle;
DeleteStyle delstyle = 0;
VALA_EXTERN gint verbose;
gint verbose = 0;
VALA_EXTERN gint noex;
gint noex = 0;
VALA_EXTERN gint matchall;
gint matchall = 0;
VALA_EXTERN gint mkdirs;
gint mkdirs = 0;
VALA_EXTERN gint patflags;
gint patflags = 0;
VALA_EXTERN gulong ndirs;
gulong ndirs = (gulong) 0;
VALA_EXTERN guint nreps;
guint nreps = (guint) 0;
VALA_EXTERN guint badreps;
guint badreps = (guint) 0;
VALA_EXTERN guint paterr;
guint paterr = (guint) 0;
VALA_EXTERN gint direrr;
gint direrr = 0;
VALA_EXTERN gboolean failed;
gboolean failed = FALSE;
VALA_EXTERN gint gotsig;
gint gotsig = 0;
VALA_EXTERN gint repbad;
gint repbad = 0;
VALA_EXTERN gchar* from;
gchar* from = NULL;
VALA_EXTERN gchar* to;
gchar* to = NULL;
VALA_EXTERN glong fromlen;
glong fromlen = 0L;
VALA_EXTERN glong tolen;
glong tolen = 0L;
VALA_EXTERN glong* stagel_vala;
VALA_EXTERN gint stagel_vala_length1;
glong* stagel_vala = NULL;
gint stagel_vala_length1 = 0;
static gint _stagel_vala_size_ = 0;
VALA_EXTERN glong* firstwild_vala;
VALA_EXTERN gint firstwild_vala_length1;
glong* firstwild_vala = NULL;
gint firstwild_vala_length1 = 0;
static gint _firstwild_vala_size_ = 0;
VALA_EXTERN glong* stager_vala;
VALA_EXTERN gint stager_vala_length1;
glong* stager_vala = NULL;
gint stager_vala_length1 = 0;
static gint _stager_vala_size_ = 0;
VALA_EXTERN gint* nwilds;
VALA_EXTERN gint nwilds_length1;
gint* nwilds = NULL;
gint nwilds_length1 = 0;
static gint _nwilds_size_ = 0;
VALA_EXTERN gint nstages;
gint nstages = 0;
VALA_EXTERN gchar* pathbuf;
VALA_EXTERN gint pathbuf_length1;
gchar* pathbuf = NULL;
gint pathbuf_length1 = 0;
static gint _pathbuf_size_ = 0;
VALA_EXTERN gchar** start;
VALA_EXTERN gint start_length1;
gchar** start = NULL;
gint start_length1 = 0;
static gint _start_size_ = 0;
VALA_EXTERN glong* length;
VALA_EXTERN gint length_length1;
glong* length = NULL;
gint length_length1 = 0;
static gint _length_size_ = 0;
VALA_EXTERN gchar* home;
gchar* home = NULL;
VALA_EXTERN glong homelen;
glong homelen = 0L;
VALA_EXTERN gchar* program_name;
gchar* program_name = NULL;

VALA_EXTERN GType file_op_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType delete_style_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType bad_style_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType recase_action_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType file_info_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType dir_info_get_type (void) G_GNUC_CONST ;
VALA_EXTERN gint vala_parsepat (void);
VALA_EXTERN void matchpat (void);
VALA_EXTERN void domatch (const gchar* cfrom,
              const gchar* cto);
static gint _vala_main (gchar** args,
                 gint args_length1);
static gint _baddel_scan_callback (REP* r,
                            gpointer self);
static gint _skipdel_scan_callback (REP* r,
                             gpointer self);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

static GType
file_op_get_type_once (void)
{
	static const GFlagsValue values[] = {{FILE_OP_NORMCOPY, "FILE_OP_NORMCOPY", "normcopy"}, {FILE_OP_OVERWRITE, "FILE_OP_OVERWRITE", "overwrite"}, {FILE_OP_NORMMOVE, "FILE_OP_NORMMOVE", "normmove"}, {FILE_OP_XMOVE, "FILE_OP_XMOVE", "xmove"}, {FILE_OP_APPEND, "FILE_OP_APPEND", "append"}, {FILE_OP_HARDLINK, "FILE_OP_HARDLINK", "hardlink"}, {FILE_OP_SYMLINK, "FILE_OP_SYMLINK", "symlink"}, {FILE_OP_COPY, "FILE_OP_COPY", "copy"}, {FILE_OP_MOVE, "FILE_OP_MOVE", "move"}, {FILE_OP_LINK, "FILE_OP_LINK", "link"}, {0, NULL, NULL}};
	GType file_op_type_id;
	file_op_type_id = g_flags_register_static ("FileOp", values);
	return file_op_type_id;
}

GType
file_op_get_type (void)
{
	static volatile gsize file_op_type_id__once = 0;
	if (g_once_init_enter (&file_op_type_id__once)) {
		GType file_op_type_id;
		file_op_type_id = file_op_get_type_once ();
		g_once_init_leave (&file_op_type_id__once, file_op_type_id);
	}
	return file_op_type_id__once;
}

static GType
delete_style_get_type_once (void)
{
	static const GEnumValue values[] = {{DELETE_STYLE_ASK, "DELETE_STYLE_ASK", "ask"}, {DELETE_STYLE_ALL, "DELETE_STYLE_ALL", "all"}, {DELETE_STYLE_NO, "DELETE_STYLE_NO", "no"}, {0, NULL, NULL}};
	GType delete_style_type_id;
	delete_style_type_id = g_enum_register_static ("DeleteStyle", values);
	return delete_style_type_id;
}

GType
delete_style_get_type (void)
{
	static volatile gsize delete_style_type_id__once = 0;
	if (g_once_init_enter (&delete_style_type_id__once)) {
		GType delete_style_type_id;
		delete_style_type_id = delete_style_get_type_once ();
		g_once_init_leave (&delete_style_type_id__once, delete_style_type_id);
	}
	return delete_style_type_id__once;
}

static GType
bad_style_get_type_once (void)
{
	static const GEnumValue values[] = {{BAD_STYLE_ASK, "BAD_STYLE_ASK", "ask"}, {BAD_STYLE_SKIP, "BAD_STYLE_SKIP", "skip"}, {BAD_STYLE_ABORT, "BAD_STYLE_ABORT", "abort"}, {0, NULL, NULL}};
	GType bad_style_type_id;
	bad_style_type_id = g_enum_register_static ("BadStyle", values);
	return bad_style_type_id;
}

GType
bad_style_get_type (void)
{
	static volatile gsize bad_style_type_id__once = 0;
	if (g_once_init_enter (&bad_style_type_id__once)) {
		GType bad_style_type_id;
		bad_style_type_id = bad_style_get_type_once ();
		g_once_init_leave (&bad_style_type_id__once, bad_style_type_id);
	}
	return bad_style_type_id__once;
}

static GType
recase_action_get_type_once (void)
{
	static const GEnumValue values[] = {{RECASE_ACTION_STAY, "RECASE_ACTION_STAY", "stay"}, {RECASE_ACTION_LOWER, "RECASE_ACTION_LOWER", "lower"}, {RECASE_ACTION_UPPER, "RECASE_ACTION_UPPER", "upper"}, {0, NULL, NULL}};
	GType recase_action_type_id;
	recase_action_type_id = g_enum_register_static ("RecaseAction", values);
	return recase_action_type_id;
}

GType
recase_action_get_type (void)
{
	static volatile gsize recase_action_type_id__once = 0;
	if (g_once_init_enter (&recase_action_type_id__once)) {
		GType recase_action_type_id;
		recase_action_type_id = recase_action_get_type_once ();
		g_once_init_leave (&recase_action_type_id__once, recase_action_type_id);
	}
	return recase_action_type_id__once;
}

static GType
file_info_get_type_once (void)
{
	static const GEnumValue values[] = {{FILE_INFO_TAKEN, "FILE_INFO_TAKEN", "taken"}, {FILE_INFO_LINKERR, "FILE_INFO_LINKERR", "linkerr"}, {FILE_INFO_INSTICKY, "FILE_INFO_INSTICKY", "insticky"}, {FILE_INFO_NODEL, "FILE_INFO_NODEL", "nodel"}, {FILE_INFO_KNOWWRITE, "FILE_INFO_KNOWWRITE", "knowwrite"}, {FILE_INFO_CANWRITE, "FILE_INFO_CANWRITE", "canwrite"}, {FILE_INFO_ISDIR, "FILE_INFO_ISDIR", "isdir"}, {FILE_INFO_ISLNK, "FILE_INFO_ISLNK", "islnk"}, {0, NULL, NULL}};
	GType file_info_type_id;
	file_info_type_id = g_enum_register_static ("FileInfo", values);
	return file_info_type_id;
}

GType
file_info_get_type (void)
{
	static volatile gsize file_info_type_id__once = 0;
	if (g_once_init_enter (&file_info_type_id__once)) {
		GType file_info_type_id;
		file_info_type_id = file_info_get_type_once ();
		g_once_init_leave (&file_info_type_id__once, file_info_type_id);
	}
	return file_info_type_id__once;
}

static GType
dir_info_get_type_once (void)
{
	static const GEnumValue values[] = {{DIR_INFO_KNOWWRITE, "DIR_INFO_KNOWWRITE", "knowwrite"}, {DIR_INFO_CANWRITE, "DIR_INFO_CANWRITE", "canwrite"}, {DIR_INFO_NONEXISTENT, "DIR_INFO_NONEXISTENT", "nonexistent"}, {0, NULL, NULL}};
	GType dir_info_type_id;
	dir_info_type_id = g_enum_register_static ("DirInfo", values);
	return dir_info_type_id;
}

GType
dir_info_get_type (void)
{
	static volatile gsize dir_info_type_id__once = 0;
	if (g_once_init_enter (&dir_info_type_id__once)) {
		GType dir_info_type_id;
		dir_info_type_id = dir_info_get_type_once ();
		g_once_init_leave (&dir_info_type_id__once, dir_info_type_id);
	}
	return dir_info_type_id__once;
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result;
#line 1501 "glib-2.0.vapi"
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
#line 1501 "glib-2.0.vapi"
	end = _tmp0_;
#line 1502 "glib-2.0.vapi"
	_tmp1_ = end;
#line 1502 "glib-2.0.vapi"
	if (_tmp1_ == NULL) {
#line 1503 "glib-2.0.vapi"
		result = maxlen;
#line 1503 "glib-2.0.vapi"
		return result;
#line 389 "mmv.c"
	} else {
		gchar* _tmp2_;
#line 1505 "glib-2.0.vapi"
		_tmp2_ = end;
#line 1505 "glib-2.0.vapi"
		result = (glong) (_tmp2_ - str);
#line 1505 "glib-2.0.vapi"
		return result;
#line 398 "mmv.c"
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result;
#line 1512 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1514 "glib-2.0.vapi"
	if (offset >= ((glong) 0)) {
#line 1514 "glib-2.0.vapi"
		_tmp0_ = len >= ((glong) 0);
#line 417 "mmv.c"
	} else {
#line 1514 "glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 421 "mmv.c"
	}
#line 1514 "glib-2.0.vapi"
	if (_tmp0_) {
#line 1516 "glib-2.0.vapi"
		string_length = string_strnlen ((gchar*) self, offset + len);
#line 427 "mmv.c"
	} else {
		gint _tmp1_;
		gint _tmp2_;
#line 1518 "glib-2.0.vapi"
		_tmp1_ = strlen (self);
#line 1518 "glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1518 "glib-2.0.vapi"
		string_length = (glong) _tmp2_;
#line 437 "mmv.c"
	}
#line 1521 "glib-2.0.vapi"
	if (offset < ((glong) 0)) {
#line 1522 "glib-2.0.vapi"
		offset = string_length + offset;
#line 1523 "glib-2.0.vapi"
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
#line 445 "mmv.c"
	} else {
#line 1525 "glib-2.0.vapi"
		g_return_val_if_fail (offset <= string_length, NULL);
#line 449 "mmv.c"
	}
#line 1527 "glib-2.0.vapi"
	if (len < ((glong) 0)) {
#line 1528 "glib-2.0.vapi"
		len = string_length - offset;
#line 455 "mmv.c"
	}
#line 1530 "glib-2.0.vapi"
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
#line 1531 "glib-2.0.vapi"
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
#line 1531 "glib-2.0.vapi"
	result = _tmp3_;
#line 1531 "glib-2.0.vapi"
	return result;
#line 465 "mmv.c"
}

static gchar
string_get (const gchar* self,
            glong index)
{
	gchar _tmp0_;
	gchar result;
#line 1283 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, '\0');
#line 1284 "glib-2.0.vapi"
	_tmp0_ = ((gchar*) self)[index];
#line 1284 "glib-2.0.vapi"
	result = _tmp0_;
#line 1284 "glib-2.0.vapi"
	return result;
#line 482 "mmv.c"
}

gint
vala_parsepat (void)
{
	glong lastname = 0L;
	gint totwilds = 0;
	gboolean instage = FALSE;
#line 1126 "mmv.vala"
	static const char TRAILESC[] = "%s -> %s : trailing %c is superfluous.\n";
#line 493 "mmv.c"
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gboolean _tmp3_;
	gchar c = '\0';
	glong p = 0L;
	const gchar* _tmp65_;
	gchar* _tmp66_;
	gchar* _tmp67_;
	gboolean _tmp68_;
	gint result;
#line 1124 "mmv.vala"
	totwilds = 0;
#line 1125 "mmv.vala"
	instage = FALSE;
#line 1129 "mmv.vala"
	lastname = (glong) 0;
#line 1130 "mmv.vala"
	_tmp0_ = from;
#line 1130 "mmv.vala"
	_tmp1_ = string_substring (_tmp0_, (glong) 0, (glong) 1);
#line 1130 "mmv.vala"
	_tmp2_ = _tmp1_;
#line 1130 "mmv.vala"
	_tmp3_ = g_strcmp0 (_tmp2_, "~" SLASHSTR) == 0;
#line 1130 "mmv.vala"
	_g_free0 (_tmp2_);
#line 1130 "mmv.vala"
	if (_tmp3_) {
#line 523 "mmv.c"
		const gchar* _tmp4_;
		gint _tmp5_;
		gint _tmp6_;
		const gchar* _tmp9_;
		const gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
#line 1131 "mmv.vala"
		_tmp4_ = home;
#line 1131 "mmv.vala"
		_tmp5_ = strlen (_tmp4_);
#line 1131 "mmv.vala"
		_tmp6_ = _tmp5_;
#line 1131 "mmv.vala"
		homelen = (glong) _tmp6_;
#line 1131 "mmv.vala"
		if ((homelen + fromlen) > ((glong) MAXPATLEN)) {
#line 542 "mmv.c"
			FILE* _tmp7_;
			const gchar* _tmp8_;
#line 1132 "mmv.vala"
			_tmp7_ = stdout;
#line 1132 "mmv.vala"
			_tmp8_ = from;
#line 1132 "mmv.vala"
			fprintf (_tmp7_, PATLONG, _tmp8_);
#line 1133 "mmv.vala"
			result = -1;
#line 1133 "mmv.vala"
			return result;
#line 555 "mmv.c"
		}
#line 1135 "mmv.vala"
		_tmp9_ = home;
#line 1135 "mmv.vala"
		_tmp10_ = from;
#line 1135 "mmv.vala"
		_tmp11_ = string_substring (_tmp10_, (glong) 1, (glong) -1);
#line 1135 "mmv.vala"
		_tmp12_ = _tmp11_;
#line 1135 "mmv.vala"
		_tmp13_ = g_strconcat (_tmp9_, _tmp12_, NULL);
#line 1135 "mmv.vala"
		_g_free0 (from);
#line 1135 "mmv.vala"
		from = _tmp13_;
#line 1135 "mmv.vala"
		_g_free0 (_tmp12_);
#line 1136 "mmv.vala"
		lastname = homelen + 1;
#line 575 "mmv.c"
	}
#line 1138 "mmv.vala"
	nstages = 0;
#line 579 "mmv.c"
	{
		gboolean _tmp14_ = FALSE;
#line 1141 "mmv.vala"
		p = lastname;
#line 1141 "mmv.vala"
		_tmp14_ = TRUE;
#line 1141 "mmv.vala"
		while (TRUE) {
#line 588 "mmv.c"
			const gchar* _tmp16_;
#line 1141 "mmv.vala"
			if (!_tmp14_) {
#line 592 "mmv.c"
				glong _tmp15_;
#line 1141 "mmv.vala"
				_tmp15_ = p;
#line 1141 "mmv.vala"
				p = _tmp15_ + 1;
#line 598 "mmv.c"
			}
#line 1141 "mmv.vala"
			_tmp14_ = FALSE;
#line 1141 "mmv.vala"
			_tmp16_ = from;
#line 1141 "mmv.vala"
			c = string_get (_tmp16_, p);
#line 1141 "mmv.vala"
			if (!(c != '\0')) {
#line 1141 "mmv.vala"
				break;
#line 610 "mmv.c"
			}
#line 1142 "mmv.vala"
			switch (c) {
#line 1142 "mmv.vala"
				case SLASH:
#line 616 "mmv.c"
				{
#line 1144 "mmv.vala"
					lastname = p + 1;
#line 1145 "mmv.vala"
					if (instage) {
#line 622 "mmv.c"
						glong* _tmp17_;
						gint _tmp17__length1;
						glong _tmp18_;
						glong* _tmp20_;
						gint _tmp20__length1;
						gint _tmp21_;
						glong _tmp22_;
#line 1146 "mmv.vala"
						_tmp17_ = firstwild_vala;
#line 1146 "mmv.vala"
						_tmp17__length1 = firstwild_vala_length1;
#line 1146 "mmv.vala"
						_tmp18_ = _tmp17_[nstages];
#line 1146 "mmv.vala"
						if (_tmp18_ == ((glong) -1)) {
#line 638 "mmv.c"
							glong* _tmp19_;
							gint _tmp19__length1;
#line 1147 "mmv.vala"
							_tmp19_ = firstwild_vala;
#line 1147 "mmv.vala"
							_tmp19__length1 = firstwild_vala_length1;
#line 1147 "mmv.vala"
							_tmp19_[nstages] = p;
#line 647 "mmv.c"
						}
#line 1148 "mmv.vala"
						_tmp20_ = stager_vala;
#line 1148 "mmv.vala"
						_tmp20__length1 = stager_vala_length1;
#line 1148 "mmv.vala"
						_tmp21_ = nstages;
#line 1148 "mmv.vala"
						nstages = _tmp21_ + 1;
#line 1148 "mmv.vala"
						_tmp22_ = p;
#line 1148 "mmv.vala"
						_tmp20_[_tmp21_] = _tmp22_;
#line 1149 "mmv.vala"
						instage = FALSE;
#line 663 "mmv.c"
					}
#line 1151 "mmv.vala"
					break;
#line 667 "mmv.c"
				}
#line 1142 "mmv.vala"
				case ';':
#line 1142 "mmv.vala"
				case '!':
#line 1142 "mmv.vala"
				case '*':
#line 1142 "mmv.vala"
				case '?':
#line 1142 "mmv.vala"
				case '[':
#line 679 "mmv.c"
				{
					gboolean _tmp23_ = FALSE;
					gint _tmp27_;
#line 1157 "mmv.vala"
					if (c == ';') {
#line 1157 "mmv.vala"
						_tmp23_ = lastname != p;
#line 687 "mmv.c"
					} else {
#line 1157 "mmv.vala"
						_tmp23_ = FALSE;
#line 691 "mmv.c"
					}
#line 1157 "mmv.vala"
					if (_tmp23_) {
#line 695 "mmv.c"
						FILE* _tmp24_;
						const gchar* _tmp25_;
						const gchar* _tmp26_;
#line 1158 "mmv.vala"
						_tmp24_ = stdout;
#line 1158 "mmv.vala"
						_tmp25_ = from;
#line 1158 "mmv.vala"
						_tmp26_ = to;
#line 1158 "mmv.vala"
						fprintf (_tmp24_, "%s -> %s : badly placed ;.\n", _tmp25_, _tmp26_);
#line 1159 "mmv.vala"
						result = -1;
#line 1159 "mmv.vala"
						return result;
#line 711 "mmv.c"
					}
#line 1161 "mmv.vala"
					_tmp27_ = totwilds;
#line 1161 "mmv.vala"
					totwilds = _tmp27_ + 1;
#line 1161 "mmv.vala"
					if (_tmp27_ == MAXWILD) {
#line 719 "mmv.c"
						const gchar* _tmp28_;
						const gchar* _tmp29_;
#line 1162 "mmv.vala"
						_tmp28_ = from;
#line 1162 "mmv.vala"
						_tmp29_ = to;
#line 1162 "mmv.vala"
						printf ("%s -> %s : too many wildcards.\n", _tmp28_, _tmp29_);
#line 1163 "mmv.vala"
						result = -1;
#line 1163 "mmv.vala"
						return result;
#line 732 "mmv.c"
					}
#line 1165 "mmv.vala"
					if (instage) {
#line 736 "mmv.c"
						gint* _tmp30_;
						gint _tmp30__length1;
						gint _tmp31_;
						glong* _tmp32_;
						gint _tmp32__length1;
						glong _tmp33_;
#line 1166 "mmv.vala"
						_tmp30_ = nwilds;
#line 1166 "mmv.vala"
						_tmp30__length1 = nwilds_length1;
#line 1166 "mmv.vala"
						_tmp31_ = _tmp30_[nstages];
#line 1166 "mmv.vala"
						_tmp30_[nstages] = _tmp31_ + 1;
#line 1167 "mmv.vala"
						_tmp32_ = firstwild_vala;
#line 1167 "mmv.vala"
						_tmp32__length1 = firstwild_vala_length1;
#line 1167 "mmv.vala"
						_tmp33_ = _tmp32_[nstages];
#line 1167 "mmv.vala"
						if (_tmp33_ == ((glong) -1)) {
#line 759 "mmv.c"
							glong* _tmp34_;
							gint _tmp34__length1;
#line 1168 "mmv.vala"
							_tmp34_ = firstwild_vala;
#line 1168 "mmv.vala"
							_tmp34__length1 = firstwild_vala_length1;
#line 1168 "mmv.vala"
							_tmp34_[nstages] = p;
#line 768 "mmv.c"
						}
					} else {
						glong* _tmp35_;
						gint _tmp35__length1;
						glong _tmp36_ = 0L;
						glong* _tmp37_;
						gint _tmp37__length1;
						gint* _tmp38_;
						gint _tmp38__length1;
#line 1170 "mmv.vala"
						_tmp35_ = stagel_vala;
#line 1170 "mmv.vala"
						_tmp35__length1 = stagel_vala_length1;
#line 1170 "mmv.vala"
						_tmp35_[nstages] = lastname;
#line 1171 "mmv.vala"
						if (c == ';') {
#line 1171 "mmv.vala"
							_tmp36_ = (glong) -1;
#line 788 "mmv.c"
						} else {
#line 1171 "mmv.vala"
							_tmp36_ = p;
#line 792 "mmv.c"
						}
#line 1171 "mmv.vala"
						_tmp37_ = firstwild_vala;
#line 1171 "mmv.vala"
						_tmp37__length1 = firstwild_vala_length1;
#line 1171 "mmv.vala"
						_tmp37_[nstages] = _tmp36_;
#line 1172 "mmv.vala"
						_tmp38_ = nwilds;
#line 1172 "mmv.vala"
						_tmp38__length1 = nwilds_length1;
#line 1172 "mmv.vala"
						_tmp38_[nstages] = 1;
#line 1173 "mmv.vala"
						instage = TRUE;
#line 808 "mmv.c"
					}
#line 1175 "mmv.vala"
					if (c != '[') {
#line 1176 "mmv.vala"
						break;
#line 814 "mmv.c"
					}
#line 1177 "mmv.vala"
					while (TRUE) {
#line 818 "mmv.c"
						const gchar* _tmp39_;
						glong _tmp40_;
#line 1177 "mmv.vala"
						_tmp39_ = from;
#line 1177 "mmv.vala"
						p = p + 1;
#line 1177 "mmv.vala"
						_tmp40_ = p;
#line 1177 "mmv.vala"
						c = string_get (_tmp39_, _tmp40_);
#line 1177 "mmv.vala"
						if (!(c != ']')) {
#line 1177 "mmv.vala"
							break;
#line 833 "mmv.c"
						}
#line 1178 "mmv.vala"
						switch (c) {
#line 1178 "mmv.vala"
							case '\0':
#line 839 "mmv.c"
							{
								const gchar* _tmp41_;
								const gchar* _tmp42_;
#line 1180 "mmv.vala"
								_tmp41_ = from;
#line 1180 "mmv.vala"
								_tmp42_ = to;
#line 1180 "mmv.vala"
								printf ("%s -> %s : missing ].\n", _tmp41_, _tmp42_);
#line 1181 "mmv.vala"
								result = -1;
#line 1181 "mmv.vala"
								return result;
#line 853 "mmv.c"
							}
#line 1178 "mmv.vala"
							case SLASH:
#line 857 "mmv.c"
							{
								const gchar* _tmp43_;
								const gchar* _tmp44_;
#line 1183 "mmv.vala"
								_tmp43_ = from;
#line 1183 "mmv.vala"
								_tmp44_ = to;
#line 1183 "mmv.vala"
								printf ("%s -> %s : '%c' cannot be part of [].\n", _tmp43_, _tmp44_, (gint) c);
#line 1185 "mmv.vala"
								result = -1;
#line 1185 "mmv.vala"
								return result;
#line 871 "mmv.c"
							}
#line 1178 "mmv.vala"
							case ESC:
#line 875 "mmv.c"
							{
								const gchar* _tmp45_;
								glong _tmp46_;
#line 1187 "mmv.vala"
								_tmp45_ = from;
#line 1187 "mmv.vala"
								p = p + 1;
#line 1187 "mmv.vala"
								_tmp46_ = p;
#line 1187 "mmv.vala"
								c = string_get (_tmp45_, _tmp46_);
#line 1187 "mmv.vala"
								if (c == '\0') {
#line 889 "mmv.c"
									const gchar* _tmp47_;
									const gchar* _tmp48_;
#line 1188 "mmv.vala"
									_tmp47_ = from;
#line 1188 "mmv.vala"
									_tmp48_ = to;
#line 1188 "mmv.vala"
									printf (TRAILESC, _tmp47_, _tmp48_, ESC);
#line 1189 "mmv.vala"
									result = -1;
#line 1189 "mmv.vala"
									return result;
#line 902 "mmv.c"
								}
#line 1191 "mmv.vala"
								break;
#line 906 "mmv.c"
							}
							default:
#line 1178 "mmv.vala"
							break;
#line 911 "mmv.c"
						}
					}
#line 1194 "mmv.vala"
					break;
#line 916 "mmv.c"
				}
#line 1142 "mmv.vala"
				case ESC:
#line 920 "mmv.c"
				{
					const gchar* _tmp49_;
					glong _tmp50_;
#line 1196 "mmv.vala"
					_tmp49_ = from;
#line 1196 "mmv.vala"
					p = p + 1;
#line 1196 "mmv.vala"
					_tmp50_ = p;
#line 1196 "mmv.vala"
					c = string_get (_tmp49_, _tmp50_);
#line 1196 "mmv.vala"
					if (c == '\0') {
#line 934 "mmv.c"
						const gchar* _tmp51_;
						const gchar* _tmp52_;
#line 1197 "mmv.vala"
						_tmp51_ = from;
#line 1197 "mmv.vala"
						_tmp52_ = to;
#line 1197 "mmv.vala"
						printf (TRAILESC, _tmp51_, _tmp52_, ESC);
#line 1198 "mmv.vala"
						result = -1;
#line 1198 "mmv.vala"
						return result;
#line 947 "mmv.c"
					}
#line 1200 "mmv.vala"
					break;
#line 951 "mmv.c"
				}
				default:
#line 1142 "mmv.vala"
				break;
#line 956 "mmv.c"
			}
		}
	}
#line 1204 "mmv.vala"
	if (instage) {
#line 962 "mmv.c"
		glong* _tmp53_;
		gint _tmp53__length1;
		glong _tmp54_;
		glong* _tmp56_;
		gint _tmp56__length1;
		gint _tmp57_;
		glong _tmp58_;
#line 1205 "mmv.vala"
		_tmp53_ = firstwild_vala;
#line 1205 "mmv.vala"
		_tmp53__length1 = firstwild_vala_length1;
#line 1205 "mmv.vala"
		_tmp54_ = _tmp53_[nstages];
#line 1205 "mmv.vala"
		if (_tmp54_ == ((glong) -1)) {
#line 978 "mmv.c"
			glong* _tmp55_;
			gint _tmp55__length1;
#line 1206 "mmv.vala"
			_tmp55_ = firstwild_vala;
#line 1206 "mmv.vala"
			_tmp55__length1 = firstwild_vala_length1;
#line 1206 "mmv.vala"
			_tmp55_[nstages] = p;
#line 987 "mmv.c"
		}
#line 1207 "mmv.vala"
		_tmp56_ = stager_vala;
#line 1207 "mmv.vala"
		_tmp56__length1 = stager_vala_length1;
#line 1207 "mmv.vala"
		_tmp57_ = nstages;
#line 1207 "mmv.vala"
		nstages = _tmp57_ + 1;
#line 1207 "mmv.vala"
		_tmp58_ = p;
#line 1207 "mmv.vala"
		_tmp56_[_tmp57_] = _tmp58_;
#line 1001 "mmv.c"
	} else {
		glong* _tmp59_;
		gint _tmp59__length1;
		gint* _tmp60_;
		gint _tmp60__length1;
		glong* _tmp61_;
		gint _tmp61__length1;
		glong* _tmp62_;
		gint _tmp62__length1;
		gint _tmp63_;
		glong _tmp64_;
#line 1209 "mmv.vala"
		_tmp59_ = stagel_vala;
#line 1209 "mmv.vala"
		_tmp59__length1 = stagel_vala_length1;
#line 1209 "mmv.vala"
		_tmp59_[nstages] = lastname;
#line 1210 "mmv.vala"
		_tmp60_ = nwilds;
#line 1210 "mmv.vala"
		_tmp60__length1 = nwilds_length1;
#line 1210 "mmv.vala"
		_tmp60_[nstages] = 0;
#line 1211 "mmv.vala"
		_tmp61_ = firstwild_vala;
#line 1211 "mmv.vala"
		_tmp61__length1 = firstwild_vala_length1;
#line 1211 "mmv.vala"
		_tmp61_[nstages] = p;
#line 1212 "mmv.vala"
		_tmp62_ = stager_vala;
#line 1212 "mmv.vala"
		_tmp62__length1 = stager_vala_length1;
#line 1212 "mmv.vala"
		_tmp63_ = nstages;
#line 1212 "mmv.vala"
		nstages = _tmp63_ + 1;
#line 1212 "mmv.vala"
		_tmp64_ = p;
#line 1212 "mmv.vala"
		_tmp62_[_tmp63_] = _tmp64_;
#line 1043 "mmv.c"
	}
#line 1216 "mmv.vala"
	lastname = (glong) 0;
#line 1217 "mmv.vala"
	_tmp65_ = to;
#line 1217 "mmv.vala"
	_tmp66_ = string_substring (_tmp65_, (glong) 0, (glong) 1);
#line 1217 "mmv.vala"
	_tmp67_ = _tmp66_;
#line 1217 "mmv.vala"
	_tmp68_ = g_strcmp0 (_tmp67_, "~" SLASHSTR) == 0;
#line 1217 "mmv.vala"
	_g_free0 (_tmp67_);
#line 1217 "mmv.vala"
	if (_tmp68_) {
#line 1059 "mmv.c"
		const gchar* _tmp69_;
		gint _tmp70_;
		gint _tmp71_;
		const gchar* _tmp74_;
		const gchar* _tmp75_;
		gchar* _tmp76_;
		gchar* _tmp77_;
		gchar* _tmp78_;
#line 1218 "mmv.vala"
		_tmp69_ = home;
#line 1218 "mmv.vala"
		_tmp70_ = strlen (_tmp69_);
#line 1218 "mmv.vala"
		_tmp71_ = _tmp70_;
#line 1218 "mmv.vala"
		homelen = (glong) _tmp71_;
#line 1218 "mmv.vala"
		if ((homelen + tolen) > ((glong) MAXPATLEN)) {
#line 1078 "mmv.c"
			FILE* _tmp72_;
			const gchar* _tmp73_;
#line 1219 "mmv.vala"
			_tmp72_ = stdout;
#line 1219 "mmv.vala"
			_tmp73_ = to;
#line 1219 "mmv.vala"
			fprintf (_tmp72_, PATLONG, _tmp73_);
#line 1220 "mmv.vala"
			result = -1;
#line 1220 "mmv.vala"
			return result;
#line 1091 "mmv.c"
		}
#line 1222 "mmv.vala"
		_tmp74_ = home;
#line 1222 "mmv.vala"
		_tmp75_ = to;
#line 1222 "mmv.vala"
		_tmp76_ = string_substring (_tmp75_, (glong) 1, (glong) -1);
#line 1222 "mmv.vala"
		_tmp77_ = _tmp76_;
#line 1222 "mmv.vala"
		_tmp78_ = g_strconcat (_tmp74_, _tmp77_, NULL);
#line 1222 "mmv.vala"
		_g_free0 (to);
#line 1222 "mmv.vala"
		to = _tmp78_;
#line 1222 "mmv.vala"
		_g_free0 (_tmp77_);
#line 1223 "mmv.vala"
		lastname = homelen + 1;
#line 1111 "mmv.c"
	}
	{
		gboolean _tmp79_ = FALSE;
#line 1226 "mmv.vala"
		p = lastname;
#line 1226 "mmv.vala"
		_tmp79_ = TRUE;
#line 1226 "mmv.vala"
		while (TRUE) {
#line 1121 "mmv.c"
			const gchar* _tmp81_;
#line 1226 "mmv.vala"
			if (!_tmp79_) {
#line 1125 "mmv.c"
				glong _tmp80_;
#line 1226 "mmv.vala"
				_tmp80_ = p;
#line 1226 "mmv.vala"
				p = _tmp80_ + 1;
#line 1131 "mmv.c"
			}
#line 1226 "mmv.vala"
			_tmp79_ = FALSE;
#line 1226 "mmv.vala"
			_tmp81_ = to;
#line 1226 "mmv.vala"
			c = string_get (_tmp81_, p);
#line 1226 "mmv.vala"
			if (!(c != '\0')) {
#line 1226 "mmv.vala"
				break;
#line 1143 "mmv.c"
			}
#line 1227 "mmv.vala"
			switch (c) {
#line 1227 "mmv.vala"
				case SLASH:
#line 1149 "mmv.c"
				{
#line 1229 "mmv.vala"
					lastname = p + 1;
#line 1230 "mmv.vala"
					break;
#line 1155 "mmv.c"
				}
#line 1227 "mmv.vala"
				case '#':
#line 1159 "mmv.c"
				{
					const gchar* _tmp82_;
					glong _tmp83_;
					gboolean _tmp84_ = FALSE;
					gint x = 0;
					gboolean _tmp92_ = FALSE;
#line 1232 "mmv.vala"
					_tmp82_ = to;
#line 1232 "mmv.vala"
					p = p + 1;
#line 1232 "mmv.vala"
					_tmp83_ = p;
#line 1232 "mmv.vala"
					c = string_get (_tmp82_, _tmp83_);
#line 1233 "mmv.vala"
					if (c == 'l') {
#line 1233 "mmv.vala"
						_tmp84_ = TRUE;
#line 1178 "mmv.c"
					} else {
#line 1233 "mmv.vala"
						_tmp84_ = c == 'u';
#line 1182 "mmv.c"
					}
#line 1233 "mmv.vala"
					if (_tmp84_) {
#line 1186 "mmv.c"
						const gchar* _tmp85_;
						glong _tmp86_;
#line 1234 "mmv.vala"
						_tmp85_ = to;
#line 1234 "mmv.vala"
						p = p + 1;
#line 1234 "mmv.vala"
						_tmp86_ = p;
#line 1234 "mmv.vala"
						c = string_get (_tmp85_, _tmp86_);
#line 1197 "mmv.c"
					}
#line 1237 "mmv.vala"
					if (!isdigit ((gint) c)) {
#line 1201 "mmv.c"
						const gchar* _tmp87_;
						const gchar* _tmp88_;
#line 1238 "mmv.vala"
						_tmp87_ = from;
#line 1238 "mmv.vala"
						_tmp88_ = to;
#line 1238 "mmv.vala"
						printf ("%s -> %s : expected digit (not '%c') after #.\n", _tmp87_, _tmp88_, (gint) c);
#line 1240 "mmv.vala"
						result = -1;
#line 1240 "mmv.vala"
						return result;
#line 1214 "mmv.c"
					}
					{
						gboolean _tmp89_ = FALSE;
#line 1243 "mmv.vala"
						x = 0;
#line 1243 "mmv.vala"
						_tmp89_ = TRUE;
#line 1243 "mmv.vala"
						while (TRUE) {
#line 1224 "mmv.c"
							const gchar* _tmp90_;
							glong _tmp91_;
#line 1243 "mmv.vala"
							if (!_tmp89_) {
#line 1243 "mmv.vala"
								x *= 10;
#line 1231 "mmv.c"
							}
#line 1243 "mmv.vala"
							_tmp89_ = FALSE;
#line 1244 "mmv.vala"
							x += (gint) (c - '0');
#line 1245 "mmv.vala"
							_tmp90_ = to;
#line 1245 "mmv.vala"
							c = string_get (_tmp90_, p + 1);
#line 1246 "mmv.vala"
							if (!isdigit ((gint) c)) {
#line 1247 "mmv.vala"
								break;
#line 1245 "mmv.c"
							}
#line 1248 "mmv.vala"
							_tmp91_ = p;
#line 1248 "mmv.vala"
							p = _tmp91_ + 1;
#line 1251 "mmv.c"
						}
					}
#line 1250 "mmv.vala"
					if (x < 1) {
#line 1250 "mmv.vala"
						_tmp92_ = TRUE;
#line 1258 "mmv.c"
					} else {
#line 1250 "mmv.vala"
						_tmp92_ = x > totwilds;
#line 1262 "mmv.c"
					}
#line 1250 "mmv.vala"
					if (_tmp92_) {
#line 1266 "mmv.c"
						const gchar* _tmp93_;
						const gchar* _tmp94_;
#line 1251 "mmv.vala"
						_tmp93_ = from;
#line 1251 "mmv.vala"
						_tmp94_ = to;
#line 1251 "mmv.vala"
						printf ("%s -> %s : wildcard #%d does not exist.\n", _tmp93_, _tmp94_, x);
#line 1253 "mmv.vala"
						result = -1;
#line 1253 "mmv.vala"
						return result;
#line 1279 "mmv.c"
					}
#line 1255 "mmv.vala"
					break;
#line 1283 "mmv.c"
				}
#line 1227 "mmv.vala"
				case ESC:
#line 1287 "mmv.c"
				{
					const gchar* _tmp95_;
					glong _tmp96_;
#line 1257 "mmv.vala"
					_tmp95_ = to;
#line 1257 "mmv.vala"
					p = p + 1;
#line 1257 "mmv.vala"
					_tmp96_ = p;
#line 1257 "mmv.vala"
					c = string_get (_tmp95_, _tmp96_);
#line 1257 "mmv.vala"
					if (c == '\0') {
#line 1301 "mmv.c"
						const gchar* _tmp97_;
						const gchar* _tmp98_;
#line 1258 "mmv.vala"
						_tmp97_ = from;
#line 1258 "mmv.vala"
						_tmp98_ = to;
#line 1258 "mmv.vala"
						printf (TRAILESC, _tmp97_, _tmp98_, ESC);
#line 1259 "mmv.vala"
						result = -1;
#line 1259 "mmv.vala"
						return result;
#line 1314 "mmv.c"
					}
#line 1261 "mmv.vala"
					break;
#line 1318 "mmv.c"
				}
				default:
#line 1227 "mmv.vala"
				break;
#line 1323 "mmv.c"
			}
		}
	}
#line 1265 "mmv.vala"
	result = 0;
#line 1265 "mmv.vala"
	return result;
#line 1331 "mmv.c"
}

void
matchpat (void)
{
#line 1270 "mmv.vala"
	if (parsepat () != 0) {
#line 1271 "mmv.vala"
		paterr = (guint) 1;
#line 1341 "mmv.c"
	} else {
		const gchar* _tmp0_;
		gchar* _tmp1_;
		gint _tmp1__length1;
		gchar** _tmp2_;
		gint _tmp2__length1;
		glong* _tmp3_;
		gint _tmp3__length1;
#line 1272 "mmv.vala"
		_tmp0_ = from;
#line 1272 "mmv.vala"
		_tmp1_ = pathbuf;
#line 1272 "mmv.vala"
		_tmp1__length1 = pathbuf_length1;
#line 1272 "mmv.vala"
		_tmp2_ = start;
#line 1272 "mmv.vala"
		_tmp2__length1 = start_length1;
#line 1272 "mmv.vala"
		_tmp3_ = length;
#line 1272 "mmv.vala"
		_tmp3__length1 = length_length1;
#line 1272 "mmv.vala"
		if (dostage (_tmp0_, _tmp1_, _tmp2_, _tmp3_, 0, 0) != 0) {
#line 1366 "mmv.c"
			FILE* _tmp4_;
			const gchar* _tmp5_;
			const gchar* _tmp6_;
#line 1273 "mmv.vala"
			_tmp4_ = stdout;
#line 1273 "mmv.vala"
			_tmp5_ = from;
#line 1273 "mmv.vala"
			_tmp6_ = to;
#line 1273 "mmv.vala"
			fprintf (_tmp4_, "%s -> %s : no match.\n", _tmp5_, _tmp6_);
#line 1274 "mmv.vala"
			paterr = (guint) 1;
#line 1380 "mmv.c"
		}
	}
}

void
domatch (const gchar* cfrom,
         const gchar* cto)
{
	gint _tmp0_;
	gint _tmp1_;
#line 1278 "mmv.vala"
	g_return_if_fail (cfrom != NULL);
#line 1278 "mmv.vala"
	g_return_if_fail (cto != NULL);
#line 1280 "mmv.vala"
	_tmp0_ = strlen (cfrom);
#line 1280 "mmv.vala"
	_tmp1_ = _tmp0_;
#line 1280 "mmv.vala"
	fromlen = (glong) _tmp1_;
#line 1280 "mmv.vala"
	if (fromlen >= ((glong) MAXPATLEN)) {
#line 1403 "mmv.c"
		FILE* _tmp2_;
#line 1281 "mmv.vala"
		_tmp2_ = stdout;
#line 1281 "mmv.vala"
		fprintf (_tmp2_, PATLONG, cfrom);
#line 1282 "mmv.vala"
		paterr = (guint) 1;
#line 1411 "mmv.c"
	} else {
		gint _tmp3_;
		gint _tmp4_;
#line 1283 "mmv.vala"
		_tmp3_ = strlen (cto);
#line 1283 "mmv.vala"
		_tmp4_ = _tmp3_;
#line 1283 "mmv.vala"
		tolen = (glong) _tmp4_;
#line 1283 "mmv.vala"
		if (tolen >= ((glong) MAXPATLEN)) {
#line 1423 "mmv.c"
			FILE* _tmp5_;
#line 1284 "mmv.vala"
			_tmp5_ = stdout;
#line 1284 "mmv.vala"
			fprintf (_tmp5_, PATLONG, cto);
#line 1285 "mmv.vala"
			paterr = (guint) 1;
#line 1431 "mmv.c"
		} else {
			gchar* _tmp6_;
			gchar* _tmp7_;
#line 1287 "mmv.vala"
			_tmp6_ = g_strdup (cfrom);
#line 1287 "mmv.vala"
			_g_free0 (from);
#line 1287 "mmv.vala"
			from = _tmp6_;
#line 1288 "mmv.vala"
			_tmp7_ = g_strdup (cto);
#line 1288 "mmv.vala"
			_g_free0 (to);
#line 1288 "mmv.vala"
			to = _tmp7_;
#line 1289 "mmv.vala"
			matchpat ();
#line 1449 "mmv.c"
		}
	}
}

static gint
_baddel_scan_callback (REP* r,
                       gpointer self)
{
	gint result;
	result = baddel (r);
#line 1771 "mmv.vala"
	return result;
#line 1462 "mmv.c"
}

static gint
_skipdel_scan_callback (REP* r,
                        gpointer self)
{
	gint result;
	result = skipdel (r);
#line 1774 "mmv.vala"
	return result;
#line 1473 "mmv.c"
}

static gint
_vala_main (gchar** args,
            gint args_length1)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* frompat = NULL;
	gchar* topat = NULL;
	gchar* _tmp2_;
	glong* _tmp3_;
	glong* _tmp4_;
	glong* _tmp5_;
	gint* _tmp11_;
	gchar** _tmp12_;
	glong* _tmp13_;
	gboolean _tmp14_ = FALSE;
	const gchar* _tmp15_;
	gchar* _tmp16_;
	const gchar* _tmp17_;
	gengetopt_args_info args_info = {0};
	gengetopt_args_info _tmp20_ = {0};
	gint _tmp21_;
	gboolean verbose = FALSE;
	gengetopt_args_info _tmp22_;
	gboolean noex = FALSE;
	gengetopt_args_info _tmp23_;
	gboolean matchall = FALSE;
	gengetopt_args_info _tmp24_;
	gboolean mkdirs = FALSE;
	gengetopt_args_info _tmp25_;
	gengetopt_args_info _tmp26_;
	gengetopt_args_info _tmp28_;
	gboolean _tmp30_ = FALSE;
	gengetopt_args_info _tmp31_;
	gboolean _tmp41_ = FALSE;
	gengetopt_args_info _tmp42_;
	gchar** _tmp43_;
	gint _tmp43__length1;
	gengetopt_args_info _tmp50_;
	gchar** _tmp51_;
	gint _tmp51__length1;
	const gchar* _tmp52_;
	gchar* _tmp53_;
	gengetopt_args_info _tmp54_;
	gchar** _tmp55_;
	gint _tmp55__length1;
	const gchar* _tmp56_;
	gchar* _tmp57_;
	const gchar* _tmp58_;
	const gchar* _tmp59_;
	gint result;
#line 1668 "mmv.vala"
	g_log_set_always_fatal (G_LOG_LEVEL_CRITICAL);
#line 1669 "mmv.vala"
	_tmp0_ = args[0];
#line 1669 "mmv.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 1669 "mmv.vala"
	_g_free0 (program_name);
#line 1669 "mmv.vala"
	program_name = _tmp1_;
#line 1672 "mmv.vala"
	_tmp2_ = g_new0 (gchar, _PC_PATH_MAX);
#line 1672 "mmv.vala"
	pathbuf = (g_free (pathbuf), NULL);
#line 1672 "mmv.vala"
	pathbuf = _tmp2_;
#line 1672 "mmv.vala"
	pathbuf_length1 = _PC_PATH_MAX;
#line 1672 "mmv.vala"
	_pathbuf_size_ = pathbuf_length1;
#line 1673 "mmv.vala"
	_tmp3_ = g_new0 (glong, MAXWILD);
#line 1673 "mmv.vala"
	stagel_vala = (g_free (stagel_vala), NULL);
#line 1673 "mmv.vala"
	stagel_vala = _tmp3_;
#line 1673 "mmv.vala"
	stagel_vala_length1 = MAXWILD;
#line 1673 "mmv.vala"
	_stagel_vala_size_ = stagel_vala_length1;
#line 1674 "mmv.vala"
	_tmp4_ = g_new0 (glong, MAXWILD);
#line 1674 "mmv.vala"
	firstwild_vala = (g_free (firstwild_vala), NULL);
#line 1674 "mmv.vala"
	firstwild_vala = _tmp4_;
#line 1674 "mmv.vala"
	firstwild_vala_length1 = MAXWILD;
#line 1674 "mmv.vala"
	_firstwild_vala_size_ = firstwild_vala_length1;
#line 1675 "mmv.vala"
	_tmp5_ = g_new0 (glong, MAXWILD);
#line 1675 "mmv.vala"
	stager_vala = (g_free (stager_vala), NULL);
#line 1675 "mmv.vala"
	stager_vala = _tmp5_;
#line 1675 "mmv.vala"
	stager_vala_length1 = MAXWILD;
#line 1675 "mmv.vala"
	_stager_vala_size_ = stager_vala_length1;
#line 1577 "mmv.c"
	{
		gint i = 0;
#line 1676 "mmv.vala"
		i = 0;
#line 1582 "mmv.c"
		{
			gboolean _tmp6_ = FALSE;
#line 1676 "mmv.vala"
			_tmp6_ = TRUE;
#line 1676 "mmv.vala"
			while (TRUE) {
#line 1589 "mmv.c"
				glong* _tmp8_;
				gint _tmp8__length1;
				glong* _tmp9_;
				gint _tmp9__length1;
				glong* _tmp10_;
				gint _tmp10__length1;
#line 1676 "mmv.vala"
				if (!_tmp6_) {
#line 1598 "mmv.c"
					gint _tmp7_;
#line 1676 "mmv.vala"
					_tmp7_ = i;
#line 1676 "mmv.vala"
					i = _tmp7_ + 1;
#line 1604 "mmv.c"
				}
#line 1676 "mmv.vala"
				_tmp6_ = FALSE;
#line 1676 "mmv.vala"
				if (!(i < MAXWILD)) {
#line 1676 "mmv.vala"
					break;
#line 1612 "mmv.c"
				}
#line 1677 "mmv.vala"
				_tmp8_ = stagel_vala;
#line 1677 "mmv.vala"
				_tmp8__length1 = stagel_vala_length1;
#line 1677 "mmv.vala"
				_tmp8_[i] = (glong) -1;
#line 1678 "mmv.vala"
				_tmp9_ = firstwild_vala;
#line 1678 "mmv.vala"
				_tmp9__length1 = firstwild_vala_length1;
#line 1678 "mmv.vala"
				_tmp9_[i] = (glong) -1;
#line 1679 "mmv.vala"
				_tmp10_ = stager_vala;
#line 1679 "mmv.vala"
				_tmp10__length1 = stager_vala_length1;
#line 1679 "mmv.vala"
				_tmp10_[i] = (glong) -1;
#line 1632 "mmv.c"
			}
		}
	}
#line 1681 "mmv.vala"
	_tmp11_ = g_new0 (gint, MAXWILD);
#line 1681 "mmv.vala"
	nwilds = (g_free (nwilds), NULL);
#line 1681 "mmv.vala"
	nwilds = _tmp11_;
#line 1681 "mmv.vala"
	nwilds_length1 = MAXWILD;
#line 1681 "mmv.vala"
	_nwilds_size_ = nwilds_length1;
#line 1682 "mmv.vala"
	_tmp12_ = g_new0 (gchar*, MAXWILD + 1);
#line 1682 "mmv.vala"
	start = (_vala_array_free (start, start_length1, (GDestroyNotify) g_free), NULL);
#line 1682 "mmv.vala"
	start = _tmp12_;
#line 1682 "mmv.vala"
	start_length1 = MAXWILD;
#line 1682 "mmv.vala"
	_start_size_ = start_length1;
#line 1683 "mmv.vala"
	_tmp13_ = g_new0 (glong, MAXWILD);
#line 1683 "mmv.vala"
	length = (g_free (length), NULL);
#line 1683 "mmv.vala"
	length = _tmp13_;
#line 1683 "mmv.vala"
	length_length1 = MAXWILD;
#line 1683 "mmv.vala"
	_length_size_ = length_length1;
#line 1687 "mmv.vala"
	_tmp15_ = g_getenv ("HOME");
#line 1687 "mmv.vala"
	_tmp16_ = g_strdup (_tmp15_);
#line 1687 "mmv.vala"
	_g_free0 (home);
#line 1687 "mmv.vala"
	home = _tmp16_;
#line 1687 "mmv.vala"
	_tmp17_ = home;
#line 1687 "mmv.vala"
	if (_tmp17_ == NULL) {
#line 1687 "mmv.vala"
		_tmp14_ = TRUE;
#line 1680 "mmv.c"
	} else {
		const gchar* _tmp18_;
#line 1687 "mmv.vala"
		_tmp18_ = home;
#line 1687 "mmv.vala"
		_tmp14_ = g_strcmp0 (_tmp18_, SLASHSTR) == 0;
#line 1687 "mmv.c"
	}
#line 1687 "mmv.vala"
	if (_tmp14_) {
#line 1691 "mmv.c"
		gchar* _tmp19_;
#line 1688 "mmv.vala"
		_tmp19_ = g_strdup ("");
#line 1688 "mmv.vala"
		_g_free0 (home);
#line 1688 "mmv.vala"
		home = _tmp19_;
#line 1699 "mmv.c"
	}
#line 1708 "mmv.vala"
	args_info = _tmp20_;
#line 1709 "mmv.vala"
	_tmp21_ = cmdline_parser ((gint) args_length1, args, &args_info);
#line 1709 "mmv.vala"
	if (_tmp21_ != 0) {
#line 1710 "mmv.vala"
		exit (EXIT_FAILURE);
#line 1709 "mmv.c"
	}
#line 1712 "mmv.vala"
	_tmp22_ = args_info;
#line 1712 "mmv.vala"
	verbose = _tmp22_.verbose_given != ((guint) 0);
#line 1713 "mmv.vala"
	_tmp23_ = args_info;
#line 1713 "mmv.vala"
	noex = _tmp23_.dryrun_given != ((guint) 0);
#line 1714 "mmv.vala"
	_tmp24_ = args_info;
#line 1714 "mmv.vala"
	matchall = _tmp24_.hidden_given != ((guint) 0);
#line 1715 "mmv.vala"
	_tmp25_ = args_info;
#line 1715 "mmv.vala"
	mkdirs = _tmp25_.makedirs_given != ((guint) 0);
#line 1717 "mmv.vala"
	delstyle = DELETE_STYLE_ASK;
#line 1718 "mmv.vala"
	_tmp26_ = args_info;
#line 1718 "mmv.vala"
	if (_tmp26_.force_given != ((guint) 0)) {
#line 1719 "mmv.vala"
		delstyle = DELETE_STYLE_ALL;
#line 1735 "mmv.c"
	} else {
		gengetopt_args_info _tmp27_;
#line 1720 "mmv.vala"
		_tmp27_ = args_info;
#line 1720 "mmv.vala"
		if (_tmp27_.protect_given != ((guint) 0)) {
#line 1721 "mmv.vala"
			delstyle = DELETE_STYLE_NO;
#line 1744 "mmv.c"
		}
	}
#line 1723 "mmv.vala"
	badstyle = BAD_STYLE_ASK;
#line 1724 "mmv.vala"
	_tmp28_ = args_info;
#line 1724 "mmv.vala"
	if (_tmp28_.go_given != ((guint) 0)) {
#line 1725 "mmv.vala"
		badstyle = BAD_STYLE_SKIP;
#line 1755 "mmv.c"
	} else {
		gengetopt_args_info _tmp29_;
#line 1726 "mmv.vala"
		_tmp29_ = args_info;
#line 1726 "mmv.vala"
		if (_tmp29_.terminate_given != ((guint) 0)) {
#line 1727 "mmv.vala"
			badstyle = BAD_STYLE_ABORT;
#line 1764 "mmv.c"
		}
	}
#line 1729 "mmv.vala"
	_tmp31_ = args_info;
#line 1729 "mmv.vala"
	if (_tmp31_.move_given != ((guint) 0)) {
#line 1729 "mmv.vala"
		_tmp30_ = TRUE;
#line 1773 "mmv.c"
	} else {
		gengetopt_args_info _tmp32_;
#line 1729 "mmv.vala"
		_tmp32_ = args_info;
#line 1729 "mmv.vala"
		_tmp30_ = _tmp32_.rename_given != ((guint) 0);
#line 1780 "mmv.c"
	}
#line 1729 "mmv.vala"
	if (_tmp30_) {
#line 1730 "mmv.vala"
		op = FILE_OP_NORMMOVE;
#line 1786 "mmv.c"
	} else {
		gengetopt_args_info _tmp33_;
#line 1731 "mmv.vala"
		_tmp33_ = args_info;
#line 1731 "mmv.vala"
		if (_tmp33_.copydel_given != ((guint) 0)) {
#line 1732 "mmv.vala"
			op = FILE_OP_XMOVE;
#line 1795 "mmv.c"
		} else {
			gengetopt_args_info _tmp34_;
#line 1733 "mmv.vala"
			_tmp34_ = args_info;
#line 1733 "mmv.vala"
			if (_tmp34_.copy_given != ((guint) 0)) {
#line 1734 "mmv.vala"
				op = FILE_OP_NORMCOPY;
#line 1804 "mmv.c"
			} else {
				gengetopt_args_info _tmp35_;
#line 1735 "mmv.vala"
				_tmp35_ = args_info;
#line 1735 "mmv.vala"
				if (_tmp35_.overwrite_given != ((guint) 0)) {
#line 1736 "mmv.vala"
					op = FILE_OP_OVERWRITE;
#line 1813 "mmv.c"
				} else {
					gengetopt_args_info _tmp36_;
#line 1737 "mmv.vala"
					_tmp36_ = args_info;
#line 1737 "mmv.vala"
					if (_tmp36_.append_given != ((guint) 0)) {
#line 1738 "mmv.vala"
						op = FILE_OP_APPEND;
#line 1822 "mmv.c"
					} else {
						gengetopt_args_info _tmp37_;
#line 1739 "mmv.vala"
						_tmp37_ = args_info;
#line 1739 "mmv.vala"
						if (_tmp37_.hardlink_given != ((guint) 0)) {
#line 1740 "mmv.vala"
							op = FILE_OP_HARDLINK;
#line 1831 "mmv.c"
						} else {
							gengetopt_args_info _tmp38_;
#line 1741 "mmv.vala"
							_tmp38_ = args_info;
#line 1741 "mmv.vala"
							if (_tmp38_.symlink_given != ((guint) 0)) {
#line 1742 "mmv.vala"
								op = FILE_OP_SYMLINK;
#line 1840 "mmv.c"
							} else {
								const gchar* _tmp39_;
#line 1744 "mmv.vala"
								_tmp39_ = program_name;
#line 1744 "mmv.vala"
								if (g_strcmp0 (_tmp39_, COPYNAME) == 0) {
#line 1745 "mmv.vala"
									op = FILE_OP_NORMCOPY;
#line 1849 "mmv.c"
								} else {
									const gchar* _tmp40_;
#line 1746 "mmv.vala"
									_tmp40_ = program_name;
#line 1746 "mmv.vala"
									if (g_strcmp0 (_tmp40_, LINKNAME) == 0) {
#line 1747 "mmv.vala"
										op = FILE_OP_HARDLINK;
#line 1858 "mmv.c"
									} else {
#line 1749 "mmv.vala"
										op = FILE_OP_XMOVE;
#line 1862 "mmv.c"
									}
								}
							}
						}
					}
				}
			}
		}
	}
#line 1752 "mmv.vala"
	if (badstyle != BAD_STYLE_ASK) {
#line 1752 "mmv.vala"
		_tmp41_ = delstyle == DELETE_STYLE_ASK;
#line 1876 "mmv.c"
	} else {
#line 1752 "mmv.vala"
		_tmp41_ = FALSE;
#line 1880 "mmv.c"
	}
#line 1752 "mmv.vala"
	if (_tmp41_) {
#line 1753 "mmv.vala"
		delstyle = DELETE_STYLE_NO;
#line 1886 "mmv.c"
	}
#line 1755 "mmv.vala"
	_tmp42_ = args_info;
#line 1755 "mmv.vala"
	_tmp43_ = _tmp42_.inputs;
#line 1755 "mmv.vala"
	_tmp43__length1 = _tmp42_.inputs_num;
#line 1755 "mmv.vala"
	if (_tmp43__length1 != 2) {
#line 1896 "mmv.c"
		gengetopt_args_info _tmp44_;
		gchar** _tmp45_;
		gint _tmp45__length1;
		gchar* _tmp46_;
		gchar* _tmp47_;
		gchar* _tmp48_;
		gchar* _tmp49_;
#line 1757 "mmv.vala"
		_tmp44_ = args_info;
#line 1757 "mmv.vala"
		_tmp45_ = _tmp44_.inputs;
#line 1757 "mmv.vala"
		_tmp45__length1 = _tmp44_.inputs_num;
#line 1757 "mmv.vala"
		_tmp46_ = g_strdup_printf ("%i", _tmp45__length1);
#line 1757 "mmv.vala"
		_tmp47_ = _tmp46_;
#line 1757 "mmv.vala"
		_tmp48_ = g_strconcat ("not 2: ", _tmp47_, NULL);
#line 1757 "mmv.vala"
		_tmp49_ = _tmp48_;
#line 1757 "mmv.vala"
		g_print ("%s", _tmp49_);
#line 1757 "mmv.vala"
		_g_free0 (_tmp49_);
#line 1757 "mmv.vala"
		_g_free0 (_tmp47_);
#line 1758 "mmv.vala"
		dup2 (STDERR_FILENO, STDOUT_FILENO);
#line 1759 "mmv.vala"
		cmdline_parser_print_help ();
#line 1760 "mmv.vala"
		exit (1);
#line 1930 "mmv.c"
	}
#line 1763 "mmv.vala"
	_tmp50_ = args_info;
#line 1763 "mmv.vala"
	_tmp51_ = _tmp50_.inputs;
#line 1763 "mmv.vala"
	_tmp51__length1 = _tmp50_.inputs_num;
#line 1763 "mmv.vala"
	_tmp52_ = _tmp51_[0];
#line 1763 "mmv.vala"
	_tmp53_ = g_strdup (_tmp52_);
#line 1763 "mmv.vala"
	_g_free0 (frompat);
#line 1763 "mmv.vala"
	frompat = _tmp53_;
#line 1764 "mmv.vala"
	_tmp54_ = args_info;
#line 1764 "mmv.vala"
	_tmp55_ = _tmp54_.inputs;
#line 1764 "mmv.vala"
	_tmp55__length1 = _tmp54_.inputs_num;
#line 1764 "mmv.vala"
	_tmp56_ = _tmp55_[1];
#line 1764 "mmv.vala"
	_tmp57_ = g_strdup (_tmp56_);
#line 1764 "mmv.vala"
	_g_free0 (topat);
#line 1764 "mmv.vala"
	topat = _tmp57_;
#line 1766 "mmv.vala"
	_tmp58_ = frompat;
#line 1766 "mmv.vala"
	_tmp59_ = topat;
#line 1766 "mmv.vala"
	domatch (_tmp58_, _tmp59_);
#line 1767 "mmv.vala"
	checkcollisions ();
#line 1768 "mmv.vala"
	findorder ();
#line 1769 "mmv.vala"
	if ((op & (FILE_OP_COPY | FILE_OP_LINK)) != 0) {
#line 1770 "mmv.vala"
		nochains ();
#line 1974 "mmv.c"
	}
#line 1771 "mmv.vala"
	scandeletes (_baddel_scan_callback, NULL);
#line 1772 "mmv.vala"
	goonordie ();
#line 1773 "mmv.vala"
	if (delstyle == DELETE_STYLE_ASK) {
#line 1774 "mmv.vala"
		scandeletes (_skipdel_scan_callback, NULL);
#line 1984 "mmv.c"
	}
#line 1775 "mmv.vala"
	doreps ();
#line 1777 "mmv.vala"
	if (failed) {
#line 1778 "mmv.vala"
		result = 2;
#line 1778 "mmv.vala"
		 (&args_info);
#line 1778 "mmv.vala"
		_g_free0 (topat);
#line 1778 "mmv.vala"
		_g_free0 (frompat);
#line 1778 "mmv.vala"
		return result;
#line 2000 "mmv.c"
	} else {
		gboolean _tmp60_ = FALSE;
#line 1779 "mmv.vala"
		if (nreps == ((guint) 0)) {
#line 2005 "mmv.c"
			gboolean _tmp61_ = FALSE;
#line 1779 "mmv.vala"
			if (paterr > ((guint) 0)) {
#line 1779 "mmv.vala"
				_tmp61_ = TRUE;
#line 2011 "mmv.c"
			} else {
#line 1779 "mmv.vala"
				_tmp61_ = badreps > ((guint) 0);
#line 2015 "mmv.c"
			}
#line 1779 "mmv.vala"
			_tmp60_ = _tmp61_;
#line 2019 "mmv.c"
		} else {
#line 1779 "mmv.vala"
			_tmp60_ = FALSE;
#line 2023 "mmv.c"
		}
#line 1779 "mmv.vala"
		if (_tmp60_) {
#line 1780 "mmv.vala"
			result = 1;
#line 1780 "mmv.vala"
			 (&args_info);
#line 1780 "mmv.vala"
			_g_free0 (topat);
#line 1780 "mmv.vala"
			_g_free0 (frompat);
#line 1780 "mmv.vala"
			return result;
#line 2037 "mmv.c"
		}
	}
#line 1781 "mmv.vala"
	result = 0;
#line 1781 "mmv.vala"
	 (&args_info);
#line 1781 "mmv.vala"
	_g_free0 (topat);
#line 1781 "mmv.vala"
	_g_free0 (frompat);
#line 1781 "mmv.vala"
	return result;
#line 2050 "mmv.c"
}

int
main (int argc,
      char ** argv)
{
#line 1667 "mmv.vala"
	return _vala_main (argv, argc);
#line 2059 "mmv.c"
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

