/* mmv.c generated by valac 0.56.0, the Vala compiler
 * generated from mmv.vala, do not modify */

/*
  mmv

  Copyright (c) 2021-2023 Reuben Thomas.
  Copyright (c) 1990 Vladimir Lanin.

  This program is distributed under the GNU GPL version 3, or, at your
  option, any later version.

  Maintainer: Reuben Thomas <rrt@sc3d.org>

  The original author of mmv was Vladimir Lanin <lanin@csd2.nyu.edu>.

  Many thanks to those who have to contributed to the design
  and/or coding of this program:

  Tom Albrecht:	initial Sys V adaptation, consultation, and testing
  Carl Mascott:	V7 adaptation
  Mark Lewis:	-n flag idea, consultation.
  Dave Bernhold:	upper/lowercase conversion idea.
  Paul Stodghill:	copy option, argv[0] checking.
  Frank Fiamingo:	consultation and testing.
  Tom Jordahl:	bug reports and testing.
  John Lukas, Hugh Redelmeyer, Barry Nelson, John Sauter,
  Phil Dench, John Nelson:
  bug reports.
*/
/* #include "config.h"*/
/* /* NAME_MAX is not guaranteed to exist and its value should really be*/
/*  * obtained with pathconf(), but that doesn't exist on mingw * /*/
/* #ifdef _WIN32*/
/* #define _POSIX_ /* For NAME_MAX in limits.h on mingw * /*/
/* #endif*/

#include <glib.h>
#include <glib-object.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>
#include <mmv.h>
#include <cmdline-vala.h>

#define ESC '\\'
#define SLASH '/'
#define APPENDNAME "mad"
#define COPYNAME "mcp"
#define LINKNAME "mln"
#define MAXWILD 20
#define MAXPATLEN ((gint) _PC_PATH_MAX)
#define INITROOM 10
#define TEMP "$$mmvtmp."
#define TOOLONG "(too long)"
#define EMPTY "(empty)"
#define SLASHSTR "/"
#define PATLONG "%.40s... : pattern too long.\n"
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

typedef enum  {
	FILE_OP_NORMCOPY = 1 << 0,
	FILE_OP_OVERWRITE = 1 << 1,
	FILE_OP_NORMMOVE = 1 << 2,
	FILE_OP_XMOVE = 1 << 3,
	FILE_OP_DIRMOVE = 1 << 4,
	FILE_OP_APPEND = 1 << 5,
	FILE_OP_HARDLINK = 1 << 6,
	FILE_OP_SYMLINK = 1 << 7,
	FILE_OP_COPY = FILE_OP_NORMCOPY | FILE_OP_OVERWRITE,
	FILE_OP_MOVE = (FILE_OP_NORMMOVE | FILE_OP_XMOVE) | FILE_OP_DIRMOVE,
	FILE_OP_LINK = FILE_OP_HARDLINK | FILE_OP_SYMLINK
} FileOp;

#define TYPE_FILE_OP (file_op_get_type ())
typedef enum  {
	DELETE_STYLE_ASK,
	DELETE_STYLE_ALL,
	DELETE_STYLE_NO
} DeleteStyle;

#define TYPE_DELETE_STYLE (delete_style_get_type ())
typedef enum  {
	BAD_STYLE_ASK,
	BAD_STYLE_SKIP,
	BAD_STYLE_ABORT
} BadStyle;

#define TYPE_BAD_STYLE (bad_style_get_type ())
typedef enum  {
	RECASE_ACTION_STAY,
	RECASE_ACTION_LOWER,
	RECASE_ACTION_UPPER
} RecaseAction;

#define TYPE_RECASE_ACTION (recase_action_get_type ())
typedef enum  {
	FILE_INFO_TAKEN = 0x01,
	FILE_INFO_LINKERR = 0x02,
	FILE_INFO_INSTICKY = 0x04,
	FILE_INFO_NODEL = 0x08,
	FILE_INFO_KNOWWRITE = 0x10,
	FILE_INFO_CANWRITE = 0x20,
	FILE_INFO_ISDIR = 0x40,
	FILE_INFO_ISLNK = 0x80
} FileInfo;

#define TYPE_FILE_INFO (file_info_get_type ())
typedef enum  {
	DIR_INFO_KNOWWRITE = 0x1,
	DIR_INFO_CANWRITE = 0x2,
	DIR_INFO_NONEXISTENT = 0x4
} DirInfo;

#define TYPE_DIR_INFO (dir_info_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))

VALA_EXTERN FileOp op;
FileOp op = 0U;
VALA_EXTERN BadStyle badstyle;
BadStyle badstyle = 0;
VALA_EXTERN DeleteStyle delstyle;
DeleteStyle delstyle = 0;
VALA_EXTERN gint verbose;
gint verbose = 0;
VALA_EXTERN gint noex;
gint noex = 0;
VALA_EXTERN gint matchall;
gint matchall = 0;
VALA_EXTERN gint mkdirs;
gint mkdirs = 0;
VALA_EXTERN gint patflags;
gint patflags = 0;
VALA_EXTERN gulong ndirs;
gulong ndirs = (gulong) 0;
VALA_EXTERN guint nreps;
guint nreps = (guint) 0;
VALA_EXTERN guint badreps;
guint badreps = (guint) 0;
VALA_EXTERN guint paterr;
guint paterr = (guint) 0;
VALA_EXTERN gint direrr;
gint direrr = 0;
VALA_EXTERN gboolean failed;
gboolean failed = FALSE;
VALA_EXTERN gint gotsig;
gint gotsig = 0;
VALA_EXTERN gint repbad;
gint repbad = 0;
VALA_EXTERN gchar* from;
gchar* from = NULL;
VALA_EXTERN gchar* to;
gchar* to = NULL;
VALA_EXTERN glong fromlen;
glong fromlen = 0L;
VALA_EXTERN glong tolen;
glong tolen = 0L;
VALA_EXTERN glong* stagel_vala;
VALA_EXTERN gint stagel_vala_length1;
glong* stagel_vala = NULL;
gint stagel_vala_length1 = 0;
static gint _stagel_vala_size_ = 0;
VALA_EXTERN glong* firstwild_vala;
VALA_EXTERN gint firstwild_vala_length1;
glong* firstwild_vala = NULL;
gint firstwild_vala_length1 = 0;
static gint _firstwild_vala_size_ = 0;
VALA_EXTERN glong* stager_vala;
VALA_EXTERN gint stager_vala_length1;
glong* stager_vala = NULL;
gint stager_vala_length1 = 0;
static gint _stager_vala_size_ = 0;
VALA_EXTERN gint* nwilds;
VALA_EXTERN gint nwilds_length1;
gint* nwilds = NULL;
gint nwilds_length1 = 0;
static gint _nwilds_size_ = 0;
VALA_EXTERN gint nstages;
gint nstages = 0;
VALA_EXTERN gchar* pathbuf;
VALA_EXTERN gint pathbuf_length1;
gchar* pathbuf = NULL;
gint pathbuf_length1 = 0;
static gint _pathbuf_size_ = 0;
VALA_EXTERN gchar** start;
VALA_EXTERN gint start_length1;
gchar** start = NULL;
gint start_length1 = 0;
static gint _start_size_ = 0;
VALA_EXTERN glong* length;
VALA_EXTERN gint length_length1;
glong* length = NULL;
gint length_length1 = 0;
static gint _length_size_ = 0;
VALA_EXTERN gchar* home;
gchar* home = NULL;
VALA_EXTERN glong homelen;
glong homelen = 0L;
VALA_EXTERN gchar* program_name;
gchar* program_name = NULL;

VALA_EXTERN GType file_op_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType delete_style_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType bad_style_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType recase_action_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType file_info_get_type (void) G_GNUC_CONST ;
VALA_EXTERN GType dir_info_get_type (void) G_GNUC_CONST ;
VALA_EXTERN gint vala_parsepat (void);
VALA_EXTERN void matchpat (void);
VALA_EXTERN void domatch (const gchar* cfrom,
              const gchar* cto);
static gint _vala_main (gchar** args,
                 gint args_length1);
static gint _baddel_scan_callback (REP* r,
                            gpointer self);
static gint _skipdel_scan_callback (REP* r,
                             gpointer self);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

static GType
file_op_get_type_once (void)
{
	static const GFlagsValue values[] = {{FILE_OP_NORMCOPY, "FILE_OP_NORMCOPY", "normcopy"}, {FILE_OP_OVERWRITE, "FILE_OP_OVERWRITE", "overwrite"}, {FILE_OP_NORMMOVE, "FILE_OP_NORMMOVE", "normmove"}, {FILE_OP_XMOVE, "FILE_OP_XMOVE", "xmove"}, {FILE_OP_DIRMOVE, "FILE_OP_DIRMOVE", "dirmove"}, {FILE_OP_APPEND, "FILE_OP_APPEND", "append"}, {FILE_OP_HARDLINK, "FILE_OP_HARDLINK", "hardlink"}, {FILE_OP_SYMLINK, "FILE_OP_SYMLINK", "symlink"}, {FILE_OP_COPY, "FILE_OP_COPY", "copy"}, {FILE_OP_MOVE, "FILE_OP_MOVE", "move"}, {FILE_OP_LINK, "FILE_OP_LINK", "link"}, {0, NULL, NULL}};
	GType file_op_type_id;
	file_op_type_id = g_flags_register_static ("FileOp", values);
	return file_op_type_id;
}

GType
file_op_get_type (void)
{
	static volatile gsize file_op_type_id__once = 0;
	if (g_once_init_enter (&file_op_type_id__once)) {
		GType file_op_type_id;
		file_op_type_id = file_op_get_type_once ();
		g_once_init_leave (&file_op_type_id__once, file_op_type_id);
	}
	return file_op_type_id__once;
}

static GType
delete_style_get_type_once (void)
{
	static const GEnumValue values[] = {{DELETE_STYLE_ASK, "DELETE_STYLE_ASK", "ask"}, {DELETE_STYLE_ALL, "DELETE_STYLE_ALL", "all"}, {DELETE_STYLE_NO, "DELETE_STYLE_NO", "no"}, {0, NULL, NULL}};
	GType delete_style_type_id;
	delete_style_type_id = g_enum_register_static ("DeleteStyle", values);
	return delete_style_type_id;
}

GType
delete_style_get_type (void)
{
	static volatile gsize delete_style_type_id__once = 0;
	if (g_once_init_enter (&delete_style_type_id__once)) {
		GType delete_style_type_id;
		delete_style_type_id = delete_style_get_type_once ();
		g_once_init_leave (&delete_style_type_id__once, delete_style_type_id);
	}
	return delete_style_type_id__once;
}

static GType
bad_style_get_type_once (void)
{
	static const GEnumValue values[] = {{BAD_STYLE_ASK, "BAD_STYLE_ASK", "ask"}, {BAD_STYLE_SKIP, "BAD_STYLE_SKIP", "skip"}, {BAD_STYLE_ABORT, "BAD_STYLE_ABORT", "abort"}, {0, NULL, NULL}};
	GType bad_style_type_id;
	bad_style_type_id = g_enum_register_static ("BadStyle", values);
	return bad_style_type_id;
}

GType
bad_style_get_type (void)
{
	static volatile gsize bad_style_type_id__once = 0;
	if (g_once_init_enter (&bad_style_type_id__once)) {
		GType bad_style_type_id;
		bad_style_type_id = bad_style_get_type_once ();
		g_once_init_leave (&bad_style_type_id__once, bad_style_type_id);
	}
	return bad_style_type_id__once;
}

static GType
recase_action_get_type_once (void)
{
	static const GEnumValue values[] = {{RECASE_ACTION_STAY, "RECASE_ACTION_STAY", "stay"}, {RECASE_ACTION_LOWER, "RECASE_ACTION_LOWER", "lower"}, {RECASE_ACTION_UPPER, "RECASE_ACTION_UPPER", "upper"}, {0, NULL, NULL}};
	GType recase_action_type_id;
	recase_action_type_id = g_enum_register_static ("RecaseAction", values);
	return recase_action_type_id;
}

GType
recase_action_get_type (void)
{
	static volatile gsize recase_action_type_id__once = 0;
	if (g_once_init_enter (&recase_action_type_id__once)) {
		GType recase_action_type_id;
		recase_action_type_id = recase_action_get_type_once ();
		g_once_init_leave (&recase_action_type_id__once, recase_action_type_id);
	}
	return recase_action_type_id__once;
}

static GType
file_info_get_type_once (void)
{
	static const GEnumValue values[] = {{FILE_INFO_TAKEN, "FILE_INFO_TAKEN", "taken"}, {FILE_INFO_LINKERR, "FILE_INFO_LINKERR", "linkerr"}, {FILE_INFO_INSTICKY, "FILE_INFO_INSTICKY", "insticky"}, {FILE_INFO_NODEL, "FILE_INFO_NODEL", "nodel"}, {FILE_INFO_KNOWWRITE, "FILE_INFO_KNOWWRITE", "knowwrite"}, {FILE_INFO_CANWRITE, "FILE_INFO_CANWRITE", "canwrite"}, {FILE_INFO_ISDIR, "FILE_INFO_ISDIR", "isdir"}, {FILE_INFO_ISLNK, "FILE_INFO_ISLNK", "islnk"}, {0, NULL, NULL}};
	GType file_info_type_id;
	file_info_type_id = g_enum_register_static ("FileInfo", values);
	return file_info_type_id;
}

GType
file_info_get_type (void)
{
	static volatile gsize file_info_type_id__once = 0;
	if (g_once_init_enter (&file_info_type_id__once)) {
		GType file_info_type_id;
		file_info_type_id = file_info_get_type_once ();
		g_once_init_leave (&file_info_type_id__once, file_info_type_id);
	}
	return file_info_type_id__once;
}

static GType
dir_info_get_type_once (void)
{
	static const GEnumValue values[] = {{DIR_INFO_KNOWWRITE, "DIR_INFO_KNOWWRITE", "knowwrite"}, {DIR_INFO_CANWRITE, "DIR_INFO_CANWRITE", "canwrite"}, {DIR_INFO_NONEXISTENT, "DIR_INFO_NONEXISTENT", "nonexistent"}, {0, NULL, NULL}};
	GType dir_info_type_id;
	dir_info_type_id = g_enum_register_static ("DirInfo", values);
	return dir_info_type_id;
}

GType
dir_info_get_type (void)
{
	static volatile gsize dir_info_type_id__once = 0;
	if (g_once_init_enter (&dir_info_type_id__once)) {
		GType dir_info_type_id;
		dir_info_type_id = dir_info_get_type_once ();
		g_once_init_leave (&dir_info_type_id__once, dir_info_type_id);
	}
	return dir_info_type_id__once;
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result;
#line 1447 "glib-2.0.vapi"
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
#line 1447 "glib-2.0.vapi"
	end = _tmp0_;
#line 1448 "glib-2.0.vapi"
	_tmp1_ = end;
#line 1448 "glib-2.0.vapi"
	if (_tmp1_ == NULL) {
#line 1449 "glib-2.0.vapi"
		result = maxlen;
#line 1449 "glib-2.0.vapi"
		return result;
#line 382 "mmv.c"
	} else {
		gchar* _tmp2_;
#line 1451 "glib-2.0.vapi"
		_tmp2_ = end;
#line 1451 "glib-2.0.vapi"
		result = (glong) (_tmp2_ - str);
#line 1451 "glib-2.0.vapi"
		return result;
#line 391 "mmv.c"
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result;
#line 1458 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1460 "glib-2.0.vapi"
	if (offset >= ((glong) 0)) {
#line 1460 "glib-2.0.vapi"
		_tmp0_ = len >= ((glong) 0);
#line 410 "mmv.c"
	} else {
#line 1460 "glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 414 "mmv.c"
	}
#line 1460 "glib-2.0.vapi"
	if (_tmp0_) {
#line 1462 "glib-2.0.vapi"
		string_length = string_strnlen ((gchar*) self, offset + len);
#line 420 "mmv.c"
	} else {
		gint _tmp1_;
		gint _tmp2_;
#line 1464 "glib-2.0.vapi"
		_tmp1_ = strlen (self);
#line 1464 "glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1464 "glib-2.0.vapi"
		string_length = (glong) _tmp2_;
#line 430 "mmv.c"
	}
#line 1467 "glib-2.0.vapi"
	if (offset < ((glong) 0)) {
#line 1468 "glib-2.0.vapi"
		offset = string_length + offset;
#line 1469 "glib-2.0.vapi"
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
#line 438 "mmv.c"
	} else {
#line 1471 "glib-2.0.vapi"
		g_return_val_if_fail (offset <= string_length, NULL);
#line 442 "mmv.c"
	}
#line 1473 "glib-2.0.vapi"
	if (len < ((glong) 0)) {
#line 1474 "glib-2.0.vapi"
		len = string_length - offset;
#line 448 "mmv.c"
	}
#line 1476 "glib-2.0.vapi"
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
#line 1477 "glib-2.0.vapi"
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
#line 1477 "glib-2.0.vapi"
	result = _tmp3_;
#line 1477 "glib-2.0.vapi"
	return result;
#line 458 "mmv.c"
}

static gchar
string_get (const gchar* self,
            glong index)
{
	gchar _tmp0_;
	gchar result;
#line 1232 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, '\0');
#line 1233 "glib-2.0.vapi"
	_tmp0_ = ((gchar*) self)[index];
#line 1233 "glib-2.0.vapi"
	result = _tmp0_;
#line 1233 "glib-2.0.vapi"
	return result;
#line 475 "mmv.c"
}

gint
vala_parsepat (void)
{
	glong lastname = 0L;
	gint totwilds = 0;
	gboolean instage = FALSE;
#line 1145 "mmv.vala"
	static const char TRAILESC[] = "%s -> %s : trailing %c is superfluous.\n";
#line 486 "mmv.c"
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gboolean _tmp3_;
	gchar c = '\0';
	glong p = 0L;
	const gchar* _tmp66_;
	gchar* _tmp67_;
	gchar* _tmp68_;
	gboolean _tmp69_;
	gint result;
#line 1143 "mmv.vala"
	totwilds = 0;
#line 1144 "mmv.vala"
	instage = FALSE;
#line 1148 "mmv.vala"
	lastname = (glong) 0;
#line 1149 "mmv.vala"
	_tmp0_ = from;
#line 1149 "mmv.vala"
	_tmp1_ = string_substring (_tmp0_, (glong) 0, (glong) 1);
#line 1149 "mmv.vala"
	_tmp2_ = _tmp1_;
#line 1149 "mmv.vala"
	_tmp3_ = g_strcmp0 (_tmp2_, "~" SLASHSTR) == 0;
#line 1149 "mmv.vala"
	_g_free0 (_tmp2_);
#line 1149 "mmv.vala"
	if (_tmp3_) {
#line 516 "mmv.c"
		const gchar* _tmp4_;
		gint _tmp5_;
		gint _tmp6_;
		const gchar* _tmp9_;
		const gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
#line 1150 "mmv.vala"
		_tmp4_ = home;
#line 1150 "mmv.vala"
		_tmp5_ = strlen (_tmp4_);
#line 1150 "mmv.vala"
		_tmp6_ = _tmp5_;
#line 1150 "mmv.vala"
		homelen = (glong) _tmp6_;
#line 1150 "mmv.vala"
		if ((homelen + fromlen) > ((glong) MAXPATLEN)) {
#line 535 "mmv.c"
			FILE* _tmp7_;
			const gchar* _tmp8_;
#line 1151 "mmv.vala"
			_tmp7_ = stdout;
#line 1151 "mmv.vala"
			_tmp8_ = from;
#line 1151 "mmv.vala"
			fprintf (_tmp7_, PATLONG, _tmp8_);
#line 1152 "mmv.vala"
			result = -1;
#line 1152 "mmv.vala"
			return result;
#line 548 "mmv.c"
		}
#line 1154 "mmv.vala"
		_tmp9_ = home;
#line 1154 "mmv.vala"
		_tmp10_ = from;
#line 1154 "mmv.vala"
		_tmp11_ = string_substring (_tmp10_, (glong) 1, (glong) -1);
#line 1154 "mmv.vala"
		_tmp12_ = _tmp11_;
#line 1154 "mmv.vala"
		_tmp13_ = g_strconcat (_tmp9_, _tmp12_, NULL);
#line 1154 "mmv.vala"
		_g_free0 (from);
#line 1154 "mmv.vala"
		from = _tmp13_;
#line 1154 "mmv.vala"
		_g_free0 (_tmp12_);
#line 1155 "mmv.vala"
		lastname = homelen + 1;
#line 568 "mmv.c"
	}
#line 1157 "mmv.vala"
	nstages = 0;
#line 572 "mmv.c"
	{
		gboolean _tmp14_ = FALSE;
#line 1160 "mmv.vala"
		p = lastname;
#line 1160 "mmv.vala"
		_tmp14_ = TRUE;
#line 1160 "mmv.vala"
		while (TRUE) {
#line 581 "mmv.c"
			const gchar* _tmp16_;
#line 1160 "mmv.vala"
			if (!_tmp14_) {
#line 585 "mmv.c"
				glong _tmp15_;
#line 1160 "mmv.vala"
				_tmp15_ = p;
#line 1160 "mmv.vala"
				p = _tmp15_ + 1;
#line 591 "mmv.c"
			}
#line 1160 "mmv.vala"
			_tmp14_ = FALSE;
#line 1160 "mmv.vala"
			_tmp16_ = from;
#line 1160 "mmv.vala"
			c = string_get (_tmp16_, p);
#line 1160 "mmv.vala"
			if (!(c != '\0')) {
#line 1160 "mmv.vala"
				break;
#line 603 "mmv.c"
			}
#line 1161 "mmv.vala"
			switch (c) {
#line 1161 "mmv.vala"
				case SLASH:
#line 609 "mmv.c"
				{
#line 1163 "mmv.vala"
					lastname = p + 1;
#line 1164 "mmv.vala"
					if (instage) {
#line 615 "mmv.c"
						glong* _tmp17_;
						gint _tmp17__length1;
						glong _tmp18_;
						glong* _tmp20_;
						gint _tmp20__length1;
						gint _tmp21_;
						glong _tmp22_;
#line 1165 "mmv.vala"
						_tmp17_ = firstwild_vala;
#line 1165 "mmv.vala"
						_tmp17__length1 = firstwild_vala_length1;
#line 1165 "mmv.vala"
						_tmp18_ = _tmp17_[nstages];
#line 1165 "mmv.vala"
						if (_tmp18_ == ((glong) -1)) {
#line 631 "mmv.c"
							glong* _tmp19_;
							gint _tmp19__length1;
#line 1166 "mmv.vala"
							_tmp19_ = firstwild_vala;
#line 1166 "mmv.vala"
							_tmp19__length1 = firstwild_vala_length1;
#line 1166 "mmv.vala"
							_tmp19_[nstages] = p;
#line 640 "mmv.c"
						}
#line 1167 "mmv.vala"
						_tmp20_ = stager_vala;
#line 1167 "mmv.vala"
						_tmp20__length1 = stager_vala_length1;
#line 1167 "mmv.vala"
						_tmp21_ = nstages;
#line 1167 "mmv.vala"
						nstages = _tmp21_ + 1;
#line 1167 "mmv.vala"
						_tmp22_ = p;
#line 1167 "mmv.vala"
						_tmp20_[_tmp21_] = _tmp22_;
#line 1168 "mmv.vala"
						instage = FALSE;
#line 656 "mmv.c"
					}
#line 1170 "mmv.vala"
					break;
#line 660 "mmv.c"
				}
#line 1161 "mmv.vala"
				case ';':
#line 1161 "mmv.vala"
				case '!':
#line 1161 "mmv.vala"
				case '*':
#line 1161 "mmv.vala"
				case '?':
#line 1161 "mmv.vala"
				case '[':
#line 672 "mmv.c"
				{
					gboolean _tmp23_ = FALSE;
					gint _tmp27_;
#line 1176 "mmv.vala"
					if (c == ';') {
#line 1176 "mmv.vala"
						_tmp23_ = lastname != p;
#line 680 "mmv.c"
					} else {
#line 1176 "mmv.vala"
						_tmp23_ = FALSE;
#line 684 "mmv.c"
					}
#line 1176 "mmv.vala"
					if (_tmp23_) {
#line 688 "mmv.c"
						FILE* _tmp24_;
						const gchar* _tmp25_;
						const gchar* _tmp26_;
#line 1177 "mmv.vala"
						_tmp24_ = stdout;
#line 1177 "mmv.vala"
						_tmp25_ = from;
#line 1177 "mmv.vala"
						_tmp26_ = to;
#line 1177 "mmv.vala"
						fprintf (_tmp24_, "%s -> %s : badly placed ;.\n", _tmp25_, _tmp26_);
#line 1178 "mmv.vala"
						result = -1;
#line 1178 "mmv.vala"
						return result;
#line 704 "mmv.c"
					}
#line 1180 "mmv.vala"
					_tmp27_ = totwilds;
#line 1180 "mmv.vala"
					totwilds = _tmp27_ + 1;
#line 1180 "mmv.vala"
					if (_tmp27_ == MAXWILD) {
#line 712 "mmv.c"
						const gchar* _tmp28_;
						const gchar* _tmp29_;
#line 1181 "mmv.vala"
						_tmp28_ = from;
#line 1181 "mmv.vala"
						_tmp29_ = to;
#line 1181 "mmv.vala"
						printf ("%s -> %s : too many wildcards.\n", _tmp28_, _tmp29_);
#line 1182 "mmv.vala"
						result = -1;
#line 1182 "mmv.vala"
						return result;
#line 725 "mmv.c"
					}
#line 1184 "mmv.vala"
					if (instage) {
#line 729 "mmv.c"
						gint* _tmp30_;
						gint _tmp30__length1;
						gint _tmp31_;
						gint _tmp32_;
						glong* _tmp33_;
						gint _tmp33__length1;
						glong _tmp34_;
#line 1185 "mmv.vala"
						_tmp30_ = nwilds;
#line 1185 "mmv.vala"
						_tmp30__length1 = nwilds_length1;
#line 1185 "mmv.vala"
						_tmp31_ = nstages;
#line 1185 "mmv.vala"
						_tmp32_ = _tmp30_[_tmp31_];
#line 1185 "mmv.vala"
						_tmp30_[_tmp31_] = _tmp32_ + 1;
#line 1186 "mmv.vala"
						_tmp33_ = firstwild_vala;
#line 1186 "mmv.vala"
						_tmp33__length1 = firstwild_vala_length1;
#line 1186 "mmv.vala"
						_tmp34_ = _tmp33_[nstages];
#line 1186 "mmv.vala"
						if (_tmp34_ == ((glong) -1)) {
#line 755 "mmv.c"
							glong* _tmp35_;
							gint _tmp35__length1;
#line 1187 "mmv.vala"
							_tmp35_ = firstwild_vala;
#line 1187 "mmv.vala"
							_tmp35__length1 = firstwild_vala_length1;
#line 1187 "mmv.vala"
							_tmp35_[nstages] = p;
#line 764 "mmv.c"
						}
					} else {
						glong* _tmp36_;
						gint _tmp36__length1;
						glong _tmp37_ = 0L;
						glong* _tmp38_;
						gint _tmp38__length1;
						gint* _tmp39_;
						gint _tmp39__length1;
#line 1189 "mmv.vala"
						_tmp36_ = stagel_vala;
#line 1189 "mmv.vala"
						_tmp36__length1 = stagel_vala_length1;
#line 1189 "mmv.vala"
						_tmp36_[nstages] = lastname;
#line 1190 "mmv.vala"
						if (c == ';') {
#line 1190 "mmv.vala"
							_tmp37_ = (glong) -1;
#line 784 "mmv.c"
						} else {
#line 1190 "mmv.vala"
							_tmp37_ = p;
#line 788 "mmv.c"
						}
#line 1190 "mmv.vala"
						_tmp38_ = firstwild_vala;
#line 1190 "mmv.vala"
						_tmp38__length1 = firstwild_vala_length1;
#line 1190 "mmv.vala"
						_tmp38_[nstages] = _tmp37_;
#line 1191 "mmv.vala"
						_tmp39_ = nwilds;
#line 1191 "mmv.vala"
						_tmp39__length1 = nwilds_length1;
#line 1191 "mmv.vala"
						_tmp39_[nstages] = 1;
#line 1192 "mmv.vala"
						instage = TRUE;
#line 804 "mmv.c"
					}
#line 1194 "mmv.vala"
					if (c != '[') {
#line 1195 "mmv.vala"
						break;
#line 810 "mmv.c"
					}
#line 1196 "mmv.vala"
					while (TRUE) {
#line 814 "mmv.c"
						const gchar* _tmp40_;
						glong _tmp41_;
#line 1196 "mmv.vala"
						_tmp40_ = from;
#line 1196 "mmv.vala"
						p = p + 1;
#line 1196 "mmv.vala"
						_tmp41_ = p;
#line 1196 "mmv.vala"
						c = string_get (_tmp40_, _tmp41_);
#line 1196 "mmv.vala"
						if (!(c != ']')) {
#line 1196 "mmv.vala"
							break;
#line 829 "mmv.c"
						}
#line 1197 "mmv.vala"
						switch (c) {
#line 1197 "mmv.vala"
							case '\0':
#line 835 "mmv.c"
							{
								const gchar* _tmp42_;
								const gchar* _tmp43_;
#line 1199 "mmv.vala"
								_tmp42_ = from;
#line 1199 "mmv.vala"
								_tmp43_ = to;
#line 1199 "mmv.vala"
								printf ("%s -> %s : missing ].\n", _tmp42_, _tmp43_);
#line 1200 "mmv.vala"
								result = -1;
#line 1200 "mmv.vala"
								return result;
#line 849 "mmv.c"
							}
#line 1197 "mmv.vala"
							case SLASH:
#line 853 "mmv.c"
							{
								const gchar* _tmp44_;
								const gchar* _tmp45_;
#line 1202 "mmv.vala"
								_tmp44_ = from;
#line 1202 "mmv.vala"
								_tmp45_ = to;
#line 1202 "mmv.vala"
								printf ("%s -> %s : '%c' cannot be part of [].\n", _tmp44_, _tmp45_, (gint) c);
#line 1204 "mmv.vala"
								result = -1;
#line 1204 "mmv.vala"
								return result;
#line 867 "mmv.c"
							}
#line 1197 "mmv.vala"
							case ESC:
#line 871 "mmv.c"
							{
								const gchar* _tmp46_;
								glong _tmp47_;
#line 1206 "mmv.vala"
								_tmp46_ = from;
#line 1206 "mmv.vala"
								p = p + 1;
#line 1206 "mmv.vala"
								_tmp47_ = p;
#line 1206 "mmv.vala"
								c = string_get (_tmp46_, _tmp47_);
#line 1206 "mmv.vala"
								if (c == '\0') {
#line 885 "mmv.c"
									const gchar* _tmp48_;
									const gchar* _tmp49_;
#line 1207 "mmv.vala"
									_tmp48_ = from;
#line 1207 "mmv.vala"
									_tmp49_ = to;
#line 1207 "mmv.vala"
									printf (TRAILESC, _tmp48_, _tmp49_, ESC);
#line 1208 "mmv.vala"
									result = -1;
#line 1208 "mmv.vala"
									return result;
#line 898 "mmv.c"
								}
#line 1210 "mmv.vala"
								break;
#line 902 "mmv.c"
							}
							default:
#line 1197 "mmv.vala"
							break;
#line 907 "mmv.c"
						}
					}
#line 1213 "mmv.vala"
					break;
#line 912 "mmv.c"
				}
#line 1161 "mmv.vala"
				case ESC:
#line 916 "mmv.c"
				{
					const gchar* _tmp50_;
					glong _tmp51_;
#line 1215 "mmv.vala"
					_tmp50_ = from;
#line 1215 "mmv.vala"
					p = p + 1;
#line 1215 "mmv.vala"
					_tmp51_ = p;
#line 1215 "mmv.vala"
					c = string_get (_tmp50_, _tmp51_);
#line 1215 "mmv.vala"
					if (c == '\0') {
#line 930 "mmv.c"
						const gchar* _tmp52_;
						const gchar* _tmp53_;
#line 1216 "mmv.vala"
						_tmp52_ = from;
#line 1216 "mmv.vala"
						_tmp53_ = to;
#line 1216 "mmv.vala"
						printf (TRAILESC, _tmp52_, _tmp53_, ESC);
#line 1217 "mmv.vala"
						result = -1;
#line 1217 "mmv.vala"
						return result;
#line 943 "mmv.c"
					}
#line 1219 "mmv.vala"
					break;
#line 947 "mmv.c"
				}
				default:
#line 1161 "mmv.vala"
				break;
#line 952 "mmv.c"
			}
		}
	}
#line 1223 "mmv.vala"
	if (instage) {
#line 958 "mmv.c"
		glong* _tmp54_;
		gint _tmp54__length1;
		glong _tmp55_;
		glong* _tmp57_;
		gint _tmp57__length1;
		gint _tmp58_;
		glong _tmp59_;
#line 1224 "mmv.vala"
		_tmp54_ = firstwild_vala;
#line 1224 "mmv.vala"
		_tmp54__length1 = firstwild_vala_length1;
#line 1224 "mmv.vala"
		_tmp55_ = _tmp54_[nstages];
#line 1224 "mmv.vala"
		if (_tmp55_ == ((glong) -1)) {
#line 974 "mmv.c"
			glong* _tmp56_;
			gint _tmp56__length1;
#line 1225 "mmv.vala"
			_tmp56_ = firstwild_vala;
#line 1225 "mmv.vala"
			_tmp56__length1 = firstwild_vala_length1;
#line 1225 "mmv.vala"
			_tmp56_[nstages] = p;
#line 983 "mmv.c"
		}
#line 1226 "mmv.vala"
		_tmp57_ = stager_vala;
#line 1226 "mmv.vala"
		_tmp57__length1 = stager_vala_length1;
#line 1226 "mmv.vala"
		_tmp58_ = nstages;
#line 1226 "mmv.vala"
		nstages = _tmp58_ + 1;
#line 1226 "mmv.vala"
		_tmp59_ = p;
#line 1226 "mmv.vala"
		_tmp57_[_tmp58_] = _tmp59_;
#line 997 "mmv.c"
	} else {
		glong* _tmp60_;
		gint _tmp60__length1;
		gint* _tmp61_;
		gint _tmp61__length1;
		glong* _tmp62_;
		gint _tmp62__length1;
		glong* _tmp63_;
		gint _tmp63__length1;
		gint _tmp64_;
		glong _tmp65_;
#line 1228 "mmv.vala"
		_tmp60_ = stagel_vala;
#line 1228 "mmv.vala"
		_tmp60__length1 = stagel_vala_length1;
#line 1228 "mmv.vala"
		_tmp60_[nstages] = lastname;
#line 1229 "mmv.vala"
		_tmp61_ = nwilds;
#line 1229 "mmv.vala"
		_tmp61__length1 = nwilds_length1;
#line 1229 "mmv.vala"
		_tmp61_[nstages] = 0;
#line 1230 "mmv.vala"
		_tmp62_ = firstwild_vala;
#line 1230 "mmv.vala"
		_tmp62__length1 = firstwild_vala_length1;
#line 1230 "mmv.vala"
		_tmp62_[nstages] = p;
#line 1231 "mmv.vala"
		_tmp63_ = stager_vala;
#line 1231 "mmv.vala"
		_tmp63__length1 = stager_vala_length1;
#line 1231 "mmv.vala"
		_tmp64_ = nstages;
#line 1231 "mmv.vala"
		nstages = _tmp64_ + 1;
#line 1231 "mmv.vala"
		_tmp65_ = p;
#line 1231 "mmv.vala"
		_tmp63_[_tmp64_] = _tmp65_;
#line 1039 "mmv.c"
	}
#line 1235 "mmv.vala"
	lastname = (glong) 0;
#line 1236 "mmv.vala"
	_tmp66_ = to;
#line 1236 "mmv.vala"
	_tmp67_ = string_substring (_tmp66_, (glong) 0, (glong) 1);
#line 1236 "mmv.vala"
	_tmp68_ = _tmp67_;
#line 1236 "mmv.vala"
	_tmp69_ = g_strcmp0 (_tmp68_, "~" SLASHSTR) == 0;
#line 1236 "mmv.vala"
	_g_free0 (_tmp68_);
#line 1236 "mmv.vala"
	if (_tmp69_) {
#line 1055 "mmv.c"
		const gchar* _tmp70_;
		gint _tmp71_;
		gint _tmp72_;
		const gchar* _tmp75_;
		const gchar* _tmp76_;
		gchar* _tmp77_;
		gchar* _tmp78_;
		gchar* _tmp79_;
#line 1237 "mmv.vala"
		_tmp70_ = home;
#line 1237 "mmv.vala"
		_tmp71_ = strlen (_tmp70_);
#line 1237 "mmv.vala"
		_tmp72_ = _tmp71_;
#line 1237 "mmv.vala"
		homelen = (glong) _tmp72_;
#line 1237 "mmv.vala"
		if ((homelen + tolen) > ((glong) MAXPATLEN)) {
#line 1074 "mmv.c"
			FILE* _tmp73_;
			const gchar* _tmp74_;
#line 1238 "mmv.vala"
			_tmp73_ = stdout;
#line 1238 "mmv.vala"
			_tmp74_ = to;
#line 1238 "mmv.vala"
			fprintf (_tmp73_, PATLONG, _tmp74_);
#line 1239 "mmv.vala"
			result = -1;
#line 1239 "mmv.vala"
			return result;
#line 1087 "mmv.c"
		}
#line 1241 "mmv.vala"
		_tmp75_ = home;
#line 1241 "mmv.vala"
		_tmp76_ = to;
#line 1241 "mmv.vala"
		_tmp77_ = string_substring (_tmp76_, (glong) 1, (glong) -1);
#line 1241 "mmv.vala"
		_tmp78_ = _tmp77_;
#line 1241 "mmv.vala"
		_tmp79_ = g_strconcat (_tmp75_, _tmp78_, NULL);
#line 1241 "mmv.vala"
		_g_free0 (to);
#line 1241 "mmv.vala"
		to = _tmp79_;
#line 1241 "mmv.vala"
		_g_free0 (_tmp78_);
#line 1242 "mmv.vala"
		lastname = homelen + 1;
#line 1107 "mmv.c"
	}
	{
		gboolean _tmp80_ = FALSE;
#line 1245 "mmv.vala"
		p = lastname;
#line 1245 "mmv.vala"
		_tmp80_ = TRUE;
#line 1245 "mmv.vala"
		while (TRUE) {
#line 1117 "mmv.c"
			const gchar* _tmp82_;
#line 1245 "mmv.vala"
			if (!_tmp80_) {
#line 1121 "mmv.c"
				glong _tmp81_;
#line 1245 "mmv.vala"
				_tmp81_ = p;
#line 1245 "mmv.vala"
				p = _tmp81_ + 1;
#line 1127 "mmv.c"
			}
#line 1245 "mmv.vala"
			_tmp80_ = FALSE;
#line 1245 "mmv.vala"
			_tmp82_ = to;
#line 1245 "mmv.vala"
			c = string_get (_tmp82_, p);
#line 1245 "mmv.vala"
			if (!(c != '\0')) {
#line 1245 "mmv.vala"
				break;
#line 1139 "mmv.c"
			}
#line 1246 "mmv.vala"
			switch (c) {
#line 1246 "mmv.vala"
				case SLASH:
#line 1145 "mmv.c"
				{
#line 1248 "mmv.vala"
					if ((op & FILE_OP_DIRMOVE) == FILE_OP_DIRMOVE) {
#line 1149 "mmv.c"
						FILE* _tmp83_;
						const gchar* _tmp84_;
						const gchar* _tmp85_;
#line 1249 "mmv.vala"
						_tmp83_ = stdout;
#line 1249 "mmv.vala"
						_tmp84_ = from;
#line 1249 "mmv.vala"
						_tmp85_ = to;
#line 1249 "mmv.vala"
						fprintf (_tmp83_, "%s -> %s : no path allowed in target under -r.\n", _tmp84_, _tmp85_);
#line 1251 "mmv.vala"
						result = -1;
#line 1251 "mmv.vala"
						return result;
#line 1165 "mmv.c"
					}
#line 1253 "mmv.vala"
					lastname = p + 1;
#line 1254 "mmv.vala"
					break;
#line 1171 "mmv.c"
				}
#line 1246 "mmv.vala"
				case '#':
#line 1175 "mmv.c"
				{
					const gchar* _tmp86_;
					glong _tmp87_;
					gboolean _tmp88_ = FALSE;
					gint x = 0;
					gboolean _tmp96_ = FALSE;
#line 1256 "mmv.vala"
					_tmp86_ = to;
#line 1256 "mmv.vala"
					p = p + 1;
#line 1256 "mmv.vala"
					_tmp87_ = p;
#line 1256 "mmv.vala"
					c = string_get (_tmp86_, _tmp87_);
#line 1257 "mmv.vala"
					if (c == 'l') {
#line 1257 "mmv.vala"
						_tmp88_ = TRUE;
#line 1194 "mmv.c"
					} else {
#line 1257 "mmv.vala"
						_tmp88_ = c == 'u';
#line 1198 "mmv.c"
					}
#line 1257 "mmv.vala"
					if (_tmp88_) {
#line 1202 "mmv.c"
						const gchar* _tmp89_;
						glong _tmp90_;
#line 1258 "mmv.vala"
						_tmp89_ = to;
#line 1258 "mmv.vala"
						p = p + 1;
#line 1258 "mmv.vala"
						_tmp90_ = p;
#line 1258 "mmv.vala"
						c = string_get (_tmp89_, _tmp90_);
#line 1213 "mmv.c"
					}
#line 1261 "mmv.vala"
					if (!isdigit ((gint) c)) {
#line 1217 "mmv.c"
						const gchar* _tmp91_;
						const gchar* _tmp92_;
#line 1262 "mmv.vala"
						_tmp91_ = from;
#line 1262 "mmv.vala"
						_tmp92_ = to;
#line 1262 "mmv.vala"
						printf ("%s -> %s : expected digit (not '%c') after #.\n", _tmp91_, _tmp92_, (gint) c);
#line 1264 "mmv.vala"
						result = -1;
#line 1264 "mmv.vala"
						return result;
#line 1230 "mmv.c"
					}
					{
						gboolean _tmp93_ = FALSE;
#line 1267 "mmv.vala"
						x = 0;
#line 1267 "mmv.vala"
						_tmp93_ = TRUE;
#line 1267 "mmv.vala"
						while (TRUE) {
#line 1240 "mmv.c"
							const gchar* _tmp94_;
							glong _tmp95_;
#line 1267 "mmv.vala"
							if (!_tmp93_) {
#line 1267 "mmv.vala"
								x *= 10;
#line 1247 "mmv.c"
							}
#line 1267 "mmv.vala"
							_tmp93_ = FALSE;
#line 1268 "mmv.vala"
							x += (gint) (c - '0');
#line 1269 "mmv.vala"
							_tmp94_ = to;
#line 1269 "mmv.vala"
							c = string_get (_tmp94_, p + 1);
#line 1270 "mmv.vala"
							if (!isdigit ((gint) c)) {
#line 1271 "mmv.vala"
								break;
#line 1261 "mmv.c"
							}
#line 1272 "mmv.vala"
							_tmp95_ = p;
#line 1272 "mmv.vala"
							p = _tmp95_ + 1;
#line 1267 "mmv.c"
						}
					}
#line 1274 "mmv.vala"
					if (x < 1) {
#line 1274 "mmv.vala"
						_tmp96_ = TRUE;
#line 1274 "mmv.c"
					} else {
#line 1274 "mmv.vala"
						_tmp96_ = x > totwilds;
#line 1278 "mmv.c"
					}
#line 1274 "mmv.vala"
					if (_tmp96_) {
#line 1282 "mmv.c"
						const gchar* _tmp97_;
						const gchar* _tmp98_;
#line 1275 "mmv.vala"
						_tmp97_ = from;
#line 1275 "mmv.vala"
						_tmp98_ = to;
#line 1275 "mmv.vala"
						printf ("%s -> %s : wildcard #%d does not exist.\n", _tmp97_, _tmp98_, x);
#line 1277 "mmv.vala"
						result = -1;
#line 1277 "mmv.vala"
						return result;
#line 1295 "mmv.c"
					}
#line 1279 "mmv.vala"
					break;
#line 1299 "mmv.c"
				}
#line 1246 "mmv.vala"
				case ESC:
#line 1303 "mmv.c"
				{
					const gchar* _tmp99_;
					glong _tmp100_;
#line 1281 "mmv.vala"
					_tmp99_ = to;
#line 1281 "mmv.vala"
					p = p + 1;
#line 1281 "mmv.vala"
					_tmp100_ = p;
#line 1281 "mmv.vala"
					c = string_get (_tmp99_, _tmp100_);
#line 1281 "mmv.vala"
					if (c == '\0') {
#line 1317 "mmv.c"
						const gchar* _tmp101_;
						const gchar* _tmp102_;
#line 1282 "mmv.vala"
						_tmp101_ = from;
#line 1282 "mmv.vala"
						_tmp102_ = to;
#line 1282 "mmv.vala"
						printf (TRAILESC, _tmp101_, _tmp102_, ESC);
#line 1283 "mmv.vala"
						result = -1;
#line 1283 "mmv.vala"
						return result;
#line 1330 "mmv.c"
					}
#line 1285 "mmv.vala"
					break;
#line 1334 "mmv.c"
				}
				default:
#line 1246 "mmv.vala"
				break;
#line 1339 "mmv.c"
			}
		}
	}
#line 1289 "mmv.vala"
	result = 0;
#line 1289 "mmv.vala"
	return result;
#line 1347 "mmv.c"
}

void
matchpat (void)
{
#line 1294 "mmv.vala"
	if (parsepat () != 0) {
#line 1295 "mmv.vala"
		paterr = (guint) 1;
#line 1357 "mmv.c"
	} else {
		const gchar* _tmp0_;
		gchar* _tmp1_;
		gint _tmp1__length1;
		gchar** _tmp2_;
		gint _tmp2__length1;
		glong* _tmp3_;
		gint _tmp3__length1;
#line 1296 "mmv.vala"
		_tmp0_ = from;
#line 1296 "mmv.vala"
		_tmp1_ = pathbuf;
#line 1296 "mmv.vala"
		_tmp1__length1 = pathbuf_length1;
#line 1296 "mmv.vala"
		_tmp2_ = start;
#line 1296 "mmv.vala"
		_tmp2__length1 = start_length1;
#line 1296 "mmv.vala"
		_tmp3_ = length;
#line 1296 "mmv.vala"
		_tmp3__length1 = length_length1;
#line 1296 "mmv.vala"
		if (dostage (_tmp0_, _tmp1_, _tmp2_, _tmp3_, 0, 0) != 0) {
#line 1382 "mmv.c"
			FILE* _tmp4_;
			const gchar* _tmp5_;
			const gchar* _tmp6_;
#line 1297 "mmv.vala"
			_tmp4_ = stdout;
#line 1297 "mmv.vala"
			_tmp5_ = from;
#line 1297 "mmv.vala"
			_tmp6_ = to;
#line 1297 "mmv.vala"
			fprintf (_tmp4_, "%s -> %s : no match.\n", _tmp5_, _tmp6_);
#line 1298 "mmv.vala"
			paterr = (guint) 1;
#line 1396 "mmv.c"
		}
	}
}

void
domatch (const gchar* cfrom,
         const gchar* cto)
{
	gint _tmp0_;
	gint _tmp1_;
#line 1302 "mmv.vala"
	g_return_if_fail (cfrom != NULL);
#line 1302 "mmv.vala"
	g_return_if_fail (cto != NULL);
#line 1304 "mmv.vala"
	_tmp0_ = strlen (cfrom);
#line 1304 "mmv.vala"
	_tmp1_ = _tmp0_;
#line 1304 "mmv.vala"
	fromlen = (glong) _tmp1_;
#line 1304 "mmv.vala"
	if (fromlen >= ((glong) MAXPATLEN)) {
#line 1419 "mmv.c"
		FILE* _tmp2_;
#line 1305 "mmv.vala"
		_tmp2_ = stdout;
#line 1305 "mmv.vala"
		fprintf (_tmp2_, PATLONG, cfrom);
#line 1306 "mmv.vala"
		paterr = (guint) 1;
#line 1427 "mmv.c"
	} else {
		gint _tmp3_;
		gint _tmp4_;
#line 1307 "mmv.vala"
		_tmp3_ = strlen (cto);
#line 1307 "mmv.vala"
		_tmp4_ = _tmp3_;
#line 1307 "mmv.vala"
		tolen = (glong) _tmp4_;
#line 1307 "mmv.vala"
		if (tolen >= ((glong) MAXPATLEN)) {
#line 1439 "mmv.c"
			FILE* _tmp5_;
#line 1308 "mmv.vala"
			_tmp5_ = stdout;
#line 1308 "mmv.vala"
			fprintf (_tmp5_, PATLONG, cto);
#line 1309 "mmv.vala"
			paterr = (guint) 1;
#line 1447 "mmv.c"
		} else {
			gchar* _tmp6_;
			gchar* _tmp7_;
#line 1311 "mmv.vala"
			_tmp6_ = g_strdup (cfrom);
#line 1311 "mmv.vala"
			_g_free0 (from);
#line 1311 "mmv.vala"
			from = _tmp6_;
#line 1312 "mmv.vala"
			_tmp7_ = g_strdup (cto);
#line 1312 "mmv.vala"
			_g_free0 (to);
#line 1312 "mmv.vala"
			to = _tmp7_;
#line 1313 "mmv.vala"
			matchpat ();
#line 1465 "mmv.c"
		}
	}
}

static gint
_baddel_scan_callback (REP* r,
                       gpointer self)
{
	gint result;
	result = baddel (r);
#line 1806 "mmv.vala"
	return result;
#line 1478 "mmv.c"
}

static gint
_skipdel_scan_callback (REP* r,
                        gpointer self)
{
	gint result;
	result = skipdel (r);
#line 1809 "mmv.vala"
	return result;
#line 1489 "mmv.c"
}

static gint
_vala_main (gchar** args,
            gint args_length1)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* frompat = NULL;
	gchar* topat = NULL;
	gchar* _tmp2_;
	glong* _tmp3_;
	glong* _tmp4_;
	glong* _tmp5_;
	gint* _tmp11_;
	gchar** _tmp12_;
	glong* _tmp13_;
	gboolean _tmp14_ = FALSE;
	const gchar* _tmp15_;
	gchar* _tmp16_;
	const gchar* _tmp17_;
	gengetopt_args_info args_info = {0};
	gengetopt_args_info _tmp20_ = {0};
	gint _tmp21_;
	gboolean verbose = FALSE;
	gengetopt_args_info _tmp22_;
	gboolean noex = FALSE;
	gengetopt_args_info _tmp23_;
	gboolean matchall = FALSE;
	gengetopt_args_info _tmp24_;
	gboolean mkdirs = FALSE;
	gengetopt_args_info _tmp25_;
	gengetopt_args_info _tmp26_;
	gengetopt_args_info _tmp28_;
	gengetopt_args_info _tmp30_;
	gboolean _tmp40_ = FALSE;
	gengetopt_args_info _tmp41_;
	gchar** _tmp42_;
	gint _tmp42__length1;
	gengetopt_args_info _tmp49_;
	gchar** _tmp50_;
	gint _tmp50__length1;
	const gchar* _tmp51_;
	gchar* _tmp52_;
	gengetopt_args_info _tmp53_;
	gchar** _tmp54_;
	gint _tmp54__length1;
	const gchar* _tmp55_;
	gchar* _tmp56_;
	const gchar* _tmp57_;
	const gchar* _tmp58_;
	gint result;
#line 1692 "mmv.vala"
	g_log_set_always_fatal (G_LOG_LEVEL_CRITICAL);
#line 1693 "mmv.vala"
	_tmp0_ = args[0];
#line 1693 "mmv.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 1693 "mmv.vala"
	_g_free0 (program_name);
#line 1693 "mmv.vala"
	program_name = _tmp1_;
#line 1696 "mmv.vala"
	_tmp2_ = g_new0 (gchar, _PC_PATH_MAX);
#line 1696 "mmv.vala"
	pathbuf = (g_free (pathbuf), NULL);
#line 1696 "mmv.vala"
	pathbuf = _tmp2_;
#line 1696 "mmv.vala"
	pathbuf_length1 = _PC_PATH_MAX;
#line 1696 "mmv.vala"
	_pathbuf_size_ = pathbuf_length1;
#line 1697 "mmv.vala"
	_tmp3_ = g_new0 (glong, MAXWILD);
#line 1697 "mmv.vala"
	stagel_vala = (g_free (stagel_vala), NULL);
#line 1697 "mmv.vala"
	stagel_vala = _tmp3_;
#line 1697 "mmv.vala"
	stagel_vala_length1 = MAXWILD;
#line 1697 "mmv.vala"
	_stagel_vala_size_ = stagel_vala_length1;
#line 1698 "mmv.vala"
	_tmp4_ = g_new0 (glong, MAXWILD);
#line 1698 "mmv.vala"
	firstwild_vala = (g_free (firstwild_vala), NULL);
#line 1698 "mmv.vala"
	firstwild_vala = _tmp4_;
#line 1698 "mmv.vala"
	firstwild_vala_length1 = MAXWILD;
#line 1698 "mmv.vala"
	_firstwild_vala_size_ = firstwild_vala_length1;
#line 1699 "mmv.vala"
	_tmp5_ = g_new0 (glong, MAXWILD);
#line 1699 "mmv.vala"
	stager_vala = (g_free (stager_vala), NULL);
#line 1699 "mmv.vala"
	stager_vala = _tmp5_;
#line 1699 "mmv.vala"
	stager_vala_length1 = MAXWILD;
#line 1699 "mmv.vala"
	_stager_vala_size_ = stager_vala_length1;
#line 1592 "mmv.c"
	{
		gint i = 0;
#line 1700 "mmv.vala"
		i = 0;
#line 1597 "mmv.c"
		{
			gboolean _tmp6_ = FALSE;
#line 1700 "mmv.vala"
			_tmp6_ = TRUE;
#line 1700 "mmv.vala"
			while (TRUE) {
#line 1604 "mmv.c"
				glong* _tmp8_;
				gint _tmp8__length1;
				glong* _tmp9_;
				gint _tmp9__length1;
				glong* _tmp10_;
				gint _tmp10__length1;
#line 1700 "mmv.vala"
				if (!_tmp6_) {
#line 1613 "mmv.c"
					gint _tmp7_;
#line 1700 "mmv.vala"
					_tmp7_ = i;
#line 1700 "mmv.vala"
					i = _tmp7_ + 1;
#line 1619 "mmv.c"
				}
#line 1700 "mmv.vala"
				_tmp6_ = FALSE;
#line 1700 "mmv.vala"
				if (!(i < MAXWILD)) {
#line 1700 "mmv.vala"
					break;
#line 1627 "mmv.c"
				}
#line 1701 "mmv.vala"
				_tmp8_ = stagel_vala;
#line 1701 "mmv.vala"
				_tmp8__length1 = stagel_vala_length1;
#line 1701 "mmv.vala"
				_tmp8_[i] = (glong) -1;
#line 1702 "mmv.vala"
				_tmp9_ = firstwild_vala;
#line 1702 "mmv.vala"
				_tmp9__length1 = firstwild_vala_length1;
#line 1702 "mmv.vala"
				_tmp9_[i] = (glong) -1;
#line 1703 "mmv.vala"
				_tmp10_ = stager_vala;
#line 1703 "mmv.vala"
				_tmp10__length1 = stager_vala_length1;
#line 1703 "mmv.vala"
				_tmp10_[i] = (glong) -1;
#line 1647 "mmv.c"
			}
		}
	}
#line 1705 "mmv.vala"
	_tmp11_ = g_new0 (gint, MAXWILD);
#line 1705 "mmv.vala"
	nwilds = (g_free (nwilds), NULL);
#line 1705 "mmv.vala"
	nwilds = _tmp11_;
#line 1705 "mmv.vala"
	nwilds_length1 = MAXWILD;
#line 1705 "mmv.vala"
	_nwilds_size_ = nwilds_length1;
#line 1706 "mmv.vala"
	_tmp12_ = g_new0 (gchar*, MAXWILD + 1);
#line 1706 "mmv.vala"
	start = (_vala_array_free (start, start_length1, (GDestroyNotify) g_free), NULL);
#line 1706 "mmv.vala"
	start = _tmp12_;
#line 1706 "mmv.vala"
	start_length1 = MAXWILD;
#line 1706 "mmv.vala"
	_start_size_ = start_length1;
#line 1707 "mmv.vala"
	_tmp13_ = g_new0 (glong, MAXWILD);
#line 1707 "mmv.vala"
	length = (g_free (length), NULL);
#line 1707 "mmv.vala"
	length = _tmp13_;
#line 1707 "mmv.vala"
	length_length1 = MAXWILD;
#line 1707 "mmv.vala"
	_length_size_ = length_length1;
#line 1711 "mmv.vala"
	_tmp15_ = g_getenv ("HOME");
#line 1711 "mmv.vala"
	_tmp16_ = g_strdup (_tmp15_);
#line 1711 "mmv.vala"
	_g_free0 (home);
#line 1711 "mmv.vala"
	home = _tmp16_;
#line 1711 "mmv.vala"
	_tmp17_ = home;
#line 1711 "mmv.vala"
	if (_tmp17_ == NULL) {
#line 1711 "mmv.vala"
		_tmp14_ = TRUE;
#line 1695 "mmv.c"
	} else {
		const gchar* _tmp18_;
#line 1711 "mmv.vala"
		_tmp18_ = home;
#line 1711 "mmv.vala"
		_tmp14_ = g_strcmp0 (_tmp18_, SLASHSTR) == 0;
#line 1702 "mmv.c"
	}
#line 1711 "mmv.vala"
	if (_tmp14_) {
#line 1706 "mmv.c"
		gchar* _tmp19_;
#line 1712 "mmv.vala"
		_tmp19_ = g_strdup ("");
#line 1712 "mmv.vala"
		_g_free0 (home);
#line 1712 "mmv.vala"
		home = _tmp19_;
#line 1714 "mmv.c"
	}
#line 1733 "mmv.vala"
	args_info = _tmp20_;
#line 1734 "mmv.vala"
	_tmp21_ = cmdline_parser ((gint) args_length1, args, &args_info);
#line 1734 "mmv.vala"
	if (_tmp21_ != 0) {
#line 1735 "mmv.vala"
		exit (EXIT_FAILURE);
#line 1724 "mmv.c"
	}
#line 1737 "mmv.vala"
	_tmp22_ = args_info;
#line 1737 "mmv.vala"
	verbose = _tmp22_.verbose_given != ((guint) 0);
#line 1738 "mmv.vala"
	_tmp23_ = args_info;
#line 1738 "mmv.vala"
	noex = _tmp23_.dryrun_given != ((guint) 0);
#line 1739 "mmv.vala"
	_tmp24_ = args_info;
#line 1739 "mmv.vala"
	matchall = _tmp24_.hidden_given != ((guint) 0);
#line 1740 "mmv.vala"
	_tmp25_ = args_info;
#line 1740 "mmv.vala"
	mkdirs = _tmp25_.makedirs_given != ((guint) 0);
#line 1742 "mmv.vala"
	delstyle = DELETE_STYLE_ASK;
#line 1743 "mmv.vala"
	_tmp26_ = args_info;
#line 1743 "mmv.vala"
	if (_tmp26_.force_given != ((guint) 0)) {
#line 1744 "mmv.vala"
		delstyle = DELETE_STYLE_ALL;
#line 1750 "mmv.c"
	} else {
		gengetopt_args_info _tmp27_;
#line 1745 "mmv.vala"
		_tmp27_ = args_info;
#line 1745 "mmv.vala"
		if (_tmp27_.protect_given != ((guint) 0)) {
#line 1746 "mmv.vala"
			delstyle = DELETE_STYLE_NO;
#line 1759 "mmv.c"
		}
	}
#line 1748 "mmv.vala"
	badstyle = BAD_STYLE_ASK;
#line 1749 "mmv.vala"
	_tmp28_ = args_info;
#line 1749 "mmv.vala"
	if (_tmp28_.go_given != ((guint) 0)) {
#line 1750 "mmv.vala"
		badstyle = BAD_STYLE_SKIP;
#line 1770 "mmv.c"
	} else {
		gengetopt_args_info _tmp29_;
#line 1751 "mmv.vala"
		_tmp29_ = args_info;
#line 1751 "mmv.vala"
		if (_tmp29_.terminate_given != ((guint) 0)) {
#line 1752 "mmv.vala"
			badstyle = BAD_STYLE_ABORT;
#line 1779 "mmv.c"
		}
	}
#line 1754 "mmv.vala"
	_tmp30_ = args_info;
#line 1754 "mmv.vala"
	if (_tmp30_.move_given != ((guint) 0)) {
#line 1755 "mmv.vala"
		op = FILE_OP_NORMMOVE;
#line 1788 "mmv.c"
	} else {
		gengetopt_args_info _tmp31_;
#line 1756 "mmv.vala"
		_tmp31_ = args_info;
#line 1756 "mmv.vala"
		if (_tmp31_.copydel_given != ((guint) 0)) {
#line 1757 "mmv.vala"
			op = FILE_OP_XMOVE;
#line 1797 "mmv.c"
		} else {
			gengetopt_args_info _tmp32_;
#line 1758 "mmv.vala"
			_tmp32_ = args_info;
#line 1758 "mmv.vala"
			if (_tmp32_.rename_given != ((guint) 0)) {
#line 1759 "mmv.vala"
				op = FILE_OP_DIRMOVE;
#line 1806 "mmv.c"
			} else {
				gengetopt_args_info _tmp33_;
#line 1760 "mmv.vala"
				_tmp33_ = args_info;
#line 1760 "mmv.vala"
				if (_tmp33_.copy_given != ((guint) 0)) {
#line 1761 "mmv.vala"
					op = FILE_OP_NORMCOPY;
#line 1815 "mmv.c"
				} else {
					gengetopt_args_info _tmp34_;
#line 1762 "mmv.vala"
					_tmp34_ = args_info;
#line 1762 "mmv.vala"
					if (_tmp34_.overwrite_given != ((guint) 0)) {
#line 1763 "mmv.vala"
						op = FILE_OP_OVERWRITE;
#line 1824 "mmv.c"
					} else {
						gengetopt_args_info _tmp35_;
#line 1764 "mmv.vala"
						_tmp35_ = args_info;
#line 1764 "mmv.vala"
						if (_tmp35_.append_given != ((guint) 0)) {
#line 1765 "mmv.vala"
							op = FILE_OP_APPEND;
#line 1833 "mmv.c"
						} else {
							gengetopt_args_info _tmp36_;
#line 1766 "mmv.vala"
							_tmp36_ = args_info;
#line 1766 "mmv.vala"
							if (_tmp36_.hardlink_given != ((guint) 0)) {
#line 1767 "mmv.vala"
								op = FILE_OP_HARDLINK;
#line 1842 "mmv.c"
							} else {
								gengetopt_args_info _tmp37_;
#line 1768 "mmv.vala"
								_tmp37_ = args_info;
#line 1768 "mmv.vala"
								if (_tmp37_.symlink_given != ((guint) 0)) {
#line 1769 "mmv.vala"
									op = FILE_OP_SYMLINK;
#line 1851 "mmv.c"
								} else {
									const gchar* _tmp38_;
#line 1771 "mmv.vala"
									_tmp38_ = program_name;
#line 1771 "mmv.vala"
									if (g_strcmp0 (_tmp38_, COPYNAME) == 0) {
#line 1772 "mmv.vala"
										op = FILE_OP_NORMCOPY;
#line 1860 "mmv.c"
									} else {
										const gchar* _tmp39_;
#line 1773 "mmv.vala"
										_tmp39_ = program_name;
#line 1773 "mmv.vala"
										if (g_strcmp0 (_tmp39_, LINKNAME) == 0) {
#line 1774 "mmv.vala"
											op = FILE_OP_HARDLINK;
#line 1869 "mmv.c"
										} else {
#line 1776 "mmv.vala"
											op = FILE_OP_XMOVE;
#line 1873 "mmv.c"
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
#line 1787 "mmv.vala"
	if (badstyle != BAD_STYLE_ASK) {
#line 1787 "mmv.vala"
		_tmp40_ = delstyle == DELETE_STYLE_ASK;
#line 1888 "mmv.c"
	} else {
#line 1787 "mmv.vala"
		_tmp40_ = FALSE;
#line 1892 "mmv.c"
	}
#line 1787 "mmv.vala"
	if (_tmp40_) {
#line 1788 "mmv.vala"
		delstyle = DELETE_STYLE_NO;
#line 1898 "mmv.c"
	}
#line 1790 "mmv.vala"
	_tmp41_ = args_info;
#line 1790 "mmv.vala"
	_tmp42_ = _tmp41_.inputs;
#line 1790 "mmv.vala"
	_tmp42__length1 = _tmp41_.inputs_num;
#line 1790 "mmv.vala"
	if (_tmp42__length1 != 2) {
#line 1908 "mmv.c"
		gengetopt_args_info _tmp43_;
		gchar** _tmp44_;
		gint _tmp44__length1;
		gchar* _tmp45_;
		gchar* _tmp46_;
		gchar* _tmp47_;
		gchar* _tmp48_;
#line 1792 "mmv.vala"
		_tmp43_ = args_info;
#line 1792 "mmv.vala"
		_tmp44_ = _tmp43_.inputs;
#line 1792 "mmv.vala"
		_tmp44__length1 = _tmp43_.inputs_num;
#line 1792 "mmv.vala"
		_tmp45_ = g_strdup_printf ("%i", _tmp44__length1);
#line 1792 "mmv.vala"
		_tmp46_ = _tmp45_;
#line 1792 "mmv.vala"
		_tmp47_ = g_strconcat ("not 2: ", _tmp46_, NULL);
#line 1792 "mmv.vala"
		_tmp48_ = _tmp47_;
#line 1792 "mmv.vala"
		g_print ("%s", _tmp48_);
#line 1792 "mmv.vala"
		_g_free0 (_tmp48_);
#line 1792 "mmv.vala"
		_g_free0 (_tmp46_);
#line 1793 "mmv.vala"
		dup2 (STDERR_FILENO, STDOUT_FILENO);
#line 1794 "mmv.vala"
		cmdline_parser_print_help ();
#line 1795 "mmv.vala"
		exit (1);
#line 1942 "mmv.c"
	}
#line 1798 "mmv.vala"
	_tmp49_ = args_info;
#line 1798 "mmv.vala"
	_tmp50_ = _tmp49_.inputs;
#line 1798 "mmv.vala"
	_tmp50__length1 = _tmp49_.inputs_num;
#line 1798 "mmv.vala"
	_tmp51_ = _tmp50_[0];
#line 1798 "mmv.vala"
	_tmp52_ = g_strdup (_tmp51_);
#line 1798 "mmv.vala"
	_g_free0 (frompat);
#line 1798 "mmv.vala"
	frompat = _tmp52_;
#line 1799 "mmv.vala"
	_tmp53_ = args_info;
#line 1799 "mmv.vala"
	_tmp54_ = _tmp53_.inputs;
#line 1799 "mmv.vala"
	_tmp54__length1 = _tmp53_.inputs_num;
#line 1799 "mmv.vala"
	_tmp55_ = _tmp54_[1];
#line 1799 "mmv.vala"
	_tmp56_ = g_strdup (_tmp55_);
#line 1799 "mmv.vala"
	_g_free0 (topat);
#line 1799 "mmv.vala"
	topat = _tmp56_;
#line 1801 "mmv.vala"
	_tmp57_ = frompat;
#line 1801 "mmv.vala"
	_tmp58_ = topat;
#line 1801 "mmv.vala"
	domatch (_tmp57_, _tmp58_);
#line 1802 "mmv.vala"
	checkcollisions ();
#line 1803 "mmv.vala"
	findorder ();
#line 1804 "mmv.vala"
	if ((op & (FILE_OP_COPY | FILE_OP_LINK)) != 0) {
#line 1805 "mmv.vala"
		nochains ();
#line 1986 "mmv.c"
	}
#line 1806 "mmv.vala"
	scandeletes (_baddel_scan_callback, NULL);
#line 1807 "mmv.vala"
	goonordie ();
#line 1808 "mmv.vala"
	if (delstyle == DELETE_STYLE_ASK) {
#line 1809 "mmv.vala"
		scandeletes (_skipdel_scan_callback, NULL);
#line 1996 "mmv.c"
	}
#line 1810 "mmv.vala"
	doreps ();
#line 1812 "mmv.vala"
	if (failed) {
#line 1813 "mmv.vala"
		result = 2;
#line 1813 "mmv.vala"
		 (&args_info);
#line 1813 "mmv.vala"
		_g_free0 (topat);
#line 1813 "mmv.vala"
		_g_free0 (frompat);
#line 1813 "mmv.vala"
		return result;
#line 2012 "mmv.c"
	} else {
		gboolean _tmp59_ = FALSE;
#line 1814 "mmv.vala"
		if (nreps == ((guint) 0)) {
#line 2017 "mmv.c"
			gboolean _tmp60_ = FALSE;
#line 1814 "mmv.vala"
			if (paterr > ((guint) 0)) {
#line 1814 "mmv.vala"
				_tmp60_ = TRUE;
#line 2023 "mmv.c"
			} else {
#line 1814 "mmv.vala"
				_tmp60_ = badreps > ((guint) 0);
#line 2027 "mmv.c"
			}
#line 1814 "mmv.vala"
			_tmp59_ = _tmp60_;
#line 2031 "mmv.c"
		} else {
#line 1814 "mmv.vala"
			_tmp59_ = FALSE;
#line 2035 "mmv.c"
		}
#line 1814 "mmv.vala"
		if (_tmp59_) {
#line 1815 "mmv.vala"
			result = 1;
#line 1815 "mmv.vala"
			 (&args_info);
#line 1815 "mmv.vala"
			_g_free0 (topat);
#line 1815 "mmv.vala"
			_g_free0 (frompat);
#line 1815 "mmv.vala"
			return result;
#line 2049 "mmv.c"
		}
	}
#line 1816 "mmv.vala"
	result = 0;
#line 1816 "mmv.vala"
	 (&args_info);
#line 1816 "mmv.vala"
	_g_free0 (topat);
#line 1816 "mmv.vala"
	_g_free0 (frompat);
#line 1816 "mmv.vala"
	return result;
#line 2062 "mmv.c"
}

int
main (int argc,
      char ** argv)
{
#line 1691 "mmv.vala"
	return _vala_main (argv, argc);
#line 2071 "mmv.c"
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

