name: C/C++ CI

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            env:
              ASAN: "yes"
            shell: bash
          - os: macos-latest
            shell: bash
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }} {0}
    steps:
    - uses: actions/checkout@v4
      with: { submodules: true }
    - name: Install dependencies (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get -y install gengetopt help2man libgee-0.8-dev
    - name: Install dependencies (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install coreutils automake gengetopt help2man libgee
        echo "$(brew --prefix m4)/bin" >> $GITHUB_PATH
    - name: Build
      run: ./bootstrap && ./configure && make V=1 && make distcheck
